services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SITE_URL=https://koopa0.dev
    restart: unless-stopped
