version: '3'

vars:
  BUILD_DIR: build
  FRONTEND_DIR: '{{.BUILD_DIR}}/frontend'
  SQL_DIR: '{{.BUILD_DIR}}/sql'

tasks:
  #----------------------------------------------------------------------------
  # Default
  #----------------------------------------------------------------------------
  default:
    desc: Build everything
    cmds:
      - task: build

  #----------------------------------------------------------------------------
  # Dependencies
  #----------------------------------------------------------------------------
  install:templ:
    desc: Install templ CLI
    status:
      - command -v templ
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest

  install:npm:
    desc: Install npm dependencies
    dir: '{{.FRONTEND_DIR}}'
    sources:
      - package.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      - npm install

  install:
    desc: Install all dependencies
    cmds:
      - task: install:templ
      - task: install:npm

  #----------------------------------------------------------------------------
  # Code Generation
  #----------------------------------------------------------------------------
  generate:
    desc: Generate templ files
    deps: [install:templ]
    sources:
      - internal/web/**/*.templ
    generates:
      - internal/web/**/*_templ.go
    cmds:
      - templ generate ./internal/web/...

  sqlc:
    desc: Generate SQL code
    dir: '{{.SQL_DIR}}'
    cmds:
      - sqlc generate

  #----------------------------------------------------------------------------
  # Frontend Build
  #----------------------------------------------------------------------------
  css:
    desc: Build Tailwind CSS
    deps: [install:npm]
    sources:
      - internal/web/static/css/app.css
      - internal/web/**/*.templ
      - '{{.FRONTEND_DIR}}/tailwind.config.js'
    generates:
      - internal/web/static/css/output.css
    cmds:
      - npx --prefix {{.FRONTEND_DIR}} tailwindcss
          -c {{.FRONTEND_DIR}}/tailwind.config.js
          -i ./internal/web/static/css/app.css
          -o ./internal/web/static/css/output.css
          --minify

  css:watch:
    desc: Watch CSS for changes
    deps: [install:npm]
    cmds:
      - npx --prefix {{.FRONTEND_DIR}} tailwindcss
          -c {{.FRONTEND_DIR}}/tailwind.config.js
          -i ./internal/web/static/css/app.css
          -o ./internal/web/static/css/output.css
          --watch

  #----------------------------------------------------------------------------
  # Build
  #----------------------------------------------------------------------------
  build:
    desc: Build production binary
    deps: [generate, css]
    cmds:
      - go build -o koopa .

  build:dev:
    desc: Build development binary (filesystem assets)
    deps: [generate, css]
    cmds:
      - go build -tags dev -o koopa .

  #----------------------------------------------------------------------------
  # Testing
  #----------------------------------------------------------------------------
  test:
    desc: Run tests
    deps: [generate, css]
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    deps: [generate, css]
    cmds:
      - go test -race ./...

  test:unit:
    desc: Run unit tests only (no testcontainers)
    deps: [generate, css]
    cmds:
      - go test -short ./...

  test:integration:
    desc: Run integration tests with testcontainers (auto-cleanup)
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - go test -race ./internal/web/handlers/... -count=1 -timeout 180s

  test:handlers:
    desc: Run handler tests with testcontainers (auto-cleanup)
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - go test -v ./internal/web/handlers/... -count=1 -timeout 180s

  test:fuzz:
    desc: Run fuzz tests (30 seconds per test)
    deps: [generate]
    cmds:
      - |
        echo "=== Running FuzzCSRFToken ==="
        go test -fuzz=FuzzCSRFToken -fuzztime=30s ./internal/web/handlers/ || true
        echo "=== Running FuzzMessageContent ==="
        go test -fuzz=FuzzMessageContent -fuzztime=30s ./internal/web/handlers/ || true
        echo "=== Running FuzzHTMLEscape ==="
        go test -fuzz=FuzzHTMLEscape -fuzztime=30s ./internal/web/handlers/ || true
        echo "=== Running FuzzToolNameEscape ==="
        go test -fuzz=FuzzToolNameEscape -fuzztime=30s ./internal/web/handlers/ || true

  test:fuzz:quick:
    desc: Run fuzz tests (10 seconds per test - quick validation)
    deps: [generate]
    cmds:
      - |
        for fuzz in FuzzCSRFToken FuzzMessageContent FuzzHTMLEscape FuzzToolNameEscape FuzzMessageIDEscape; do
          echo "=== Running $fuzz ==="
          go test -fuzz=$fuzz -fuzztime=10s ./internal/web/handlers/ || true
        done

  test:cover:
    desc: Run tests with coverage
    deps: [generate, css]
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  test:embed:
    desc: Verify embedded static assets (production build only)
    deps: [generate, css]
    cmds:
      - go test -v ./internal/web/static/

  #----------------------------------------------------------------------------
  # E2E Testing (Playwright-Go)
  #----------------------------------------------------------------------------
  test:e2e:
    desc: Run all E2E tests with Playwright (requires browser)
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - echo "=== E2E Browser Tests ==="
      - go test -tags=e2e -v ./internal/web/... -count=1 -timeout 300s

  test:e2e:chat:
    desc: Run E2E chat tests only
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - go test -tags=e2e -v ./internal/web/... -run "TestE2E_Chat" -count=1 -timeout 180s

  test:e2e:components:
    desc: Run E2E component tests only
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - go test -tags=e2e -v ./internal/web/... -run "TestE2E_Component" -count=1 -timeout 180s

  test:e2e:accessibility:
    desc: Run E2E accessibility tests only (axe-core)
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - go test -tags=e2e -v ./internal/web/... -run "TestE2E_Accessibility" -count=1 -timeout 180s

  test:e2e:responsive:
    desc: Run E2E responsive layout tests only
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - go test -tags=e2e -v ./internal/web/... -run "TestE2E_Responsive" -count=1 -timeout 180s

  test:e2e:install:
    desc: Install Playwright browsers for E2E testing
    cmds:
      - go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps chromium

  test:all:
    desc: Run all tests with cleanup (unit + integration + fuzz)
    deps: [generate, css, docker:clean]
    cmds:
      - defer: task docker:clean
      - echo "=== Unit Tests ==="
      - go test -short ./...
      - echo "=== Integration Tests (with testcontainers) ==="
      - go test -race ./internal/web/handlers/... -count=1 -timeout 180s
      - echo "=== Fuzz Tests (quick) ==="
      - task: test:fuzz:quick
      - echo "=== All tests completed ==="

  #----------------------------------------------------------------------------
  # Quality
  #----------------------------------------------------------------------------
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - templ fmt ./internal/web/...

  check:
    desc: Run all checks (lint, test, build)
    cmds:
      - task: lint
      - task: test:race
      - task: build

  #----------------------------------------------------------------------------
  # Development
  #----------------------------------------------------------------------------
  dev:
    desc: Run in development mode
    deps: [generate, css]
    cmds:
      - echo "Run 'task css:watch' in another terminal for CSS hot reload"
      - go run ./cmd/koopa

  #----------------------------------------------------------------------------
  # Cleanup
  #----------------------------------------------------------------------------
  clean:
    desc: Remove generated files and binaries
    cmds:
      - find ./internal/web -name "*_templ.go" -delete 2>/dev/null || true
      - rm -f ./internal/web/static/css/output.css
      - rm -f koopa tui.test
      - rm -f coverage.out coverage.html

  clean:all:
    desc: Remove everything including node_modules
    cmds:
      - task: clean
      - rm -rf {{.FRONTEND_DIR}}/node_modules

  docker:clean:
    desc: Clean up Docker testcontainers and networks
    cmds:
      - echo "=== Cleaning Docker testcontainers ==="
      - docker ps -aq --filter "label=org.testcontainers=true" | xargs -r docker rm -f 2>/dev/null || true
      - docker ps -aq --filter "ancestor=postgres" --filter "status=exited" | xargs -r docker rm -f 2>/dev/null || true
      - docker ps -aq --filter "ancestor=postgres" --filter "status=created" | xargs -r docker rm -f 2>/dev/null || true
      - echo "=== Cleaning Docker networks ==="
      - docker network ls --filter "name=testcontainers" -q | xargs -r docker network rm 2>/dev/null || true
      - docker network prune -f 2>/dev/null || true
      - echo "=== Docker cleanup complete ==="
