version: '3'

vars:
  BUILD_DIR: build
  FRONTEND_DIR: '{{.BUILD_DIR}}/frontend'
  SQL_DIR: '{{.BUILD_DIR}}/sql'

tasks:
  #----------------------------------------------------------------------------
  # Default
  #----------------------------------------------------------------------------
  default:
    desc: Build everything
    cmds:
      - task: build

  #----------------------------------------------------------------------------
  # Dependencies
  #----------------------------------------------------------------------------
  install:templ:
    desc: Install templ CLI
    status:
      - command -v templ
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest

  install:npm:
    desc: Install npm dependencies
    dir: '{{.FRONTEND_DIR}}'
    sources:
      - package.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      - npm install

  install:
    desc: Install all dependencies
    cmds:
      - task: install:templ
      - task: install:npm

  #----------------------------------------------------------------------------
  # Code Generation
  #----------------------------------------------------------------------------
  generate:
    desc: Generate templ files
    deps: [install:templ]
    sources:
      - internal/web/**/*.templ
    generates:
      - internal/web/**/*_templ.go
    cmds:
      - templ generate ./internal/web/...

  sqlc:
    desc: Generate SQL code
    dir: '{{.SQL_DIR}}'
    cmds:
      - sqlc generate

  #----------------------------------------------------------------------------
  # Frontend Build
  #----------------------------------------------------------------------------
  css:
    desc: Build Tailwind CSS
    deps: [install:npm]
    sources:
      - internal/web/static/css/app.css
      - internal/web/**/*.templ
      - '{{.FRONTEND_DIR}}/tailwind.config.js'
    generates:
      - internal/web/static/css/output.css
    cmds:
      - npx --prefix {{.FRONTEND_DIR}} tailwindcss
          -c {{.FRONTEND_DIR}}/tailwind.config.js
          -i ./internal/web/static/css/app.css
          -o ./internal/web/static/css/output.css
          --minify

  css:watch:
    desc: Watch CSS for changes
    deps: [install:npm]
    cmds:
      - npx --prefix {{.FRONTEND_DIR}} tailwindcss
          -c {{.FRONTEND_DIR}}/tailwind.config.js
          -i ./internal/web/static/css/app.css
          -o ./internal/web/static/css/output.css
          --watch

  #----------------------------------------------------------------------------
  # Build
  #----------------------------------------------------------------------------
  build:
    desc: Build production binary
    deps: [generate, css]
    cmds:
      - go build -o koopa .

  build:dev:
    desc: Build development binary (filesystem assets)
    deps: [generate, css]
    cmds:
      - go build -tags dev -o koopa .

  #----------------------------------------------------------------------------
  # Testing
  #----------------------------------------------------------------------------
  test:
    desc: Run tests
    deps: [generate, css]
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    deps: [generate, css]
    cmds:
      - go test -race ./...

  test:fuzz:
    desc: Run fuzz tests (30 seconds)
    deps: [generate]
    cmds:
      - go test -fuzz=FuzzChatInput -fuzztime=30s ./internal/web/handlers/ || true

  test:cover:
    desc: Run tests with coverage
    deps: [generate, css]
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  test:embed:
    desc: Verify embedded static assets (production build only)
    deps: [generate, css]
    cmds:
      - go test -v ./internal/web/static/

  #----------------------------------------------------------------------------
  # Quality
  #----------------------------------------------------------------------------
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - templ fmt ./internal/web/...

  check:
    desc: Run all checks (lint, test, build)
    cmds:
      - task: lint
      - task: test:race
      - task: build

  #----------------------------------------------------------------------------
  # Development
  #----------------------------------------------------------------------------
  dev:
    desc: Run in development mode
    deps: [generate, css]
    cmds:
      - echo "Run 'task css:watch' in another terminal for CSS hot reload"
      - go run ./cmd/koopa

  #----------------------------------------------------------------------------
  # Cleanup
  #----------------------------------------------------------------------------
  clean:
    desc: Remove generated files and binaries
    cmds:
      - find ./internal/web -name "*_templ.go" -delete 2>/dev/null || true
      - rm -f ./internal/web/static/css/output.css
      - rm -f koopa koopa-cli tui.test
      - rm -f coverage.out coverage.html

  clean:all:
    desc: Remove everything including node_modules
    cmds:
      - task: clean
      - rm -rf {{.FRONTEND_DIR}}/node_modules
