version: '3'

vars:
  BUILD_DIR: build
  SQL_DIR: '{{.BUILD_DIR}}/sql'

tasks:
  #----------------------------------------------------------------------------
  # Default
  #----------------------------------------------------------------------------
  default:
    desc: Build everything
    cmds:
      - task: build

  #----------------------------------------------------------------------------
  # Code Generation
  #----------------------------------------------------------------------------
  sqlc:
    desc: Generate SQL code
    dir: '{{.SQL_DIR}}'
    cmds:
      - sqlc generate

  #----------------------------------------------------------------------------
  # Build
  #----------------------------------------------------------------------------
  build:
    desc: Build production binary
    cmds:
      - go build -o koopa .

  #----------------------------------------------------------------------------
  # Testing
  #----------------------------------------------------------------------------
  test:
    desc: Run tests
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race ./...

  test:unit:
    desc: Run unit tests only (no testcontainers)
    cmds:
      - go test -short ./...

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  test:all:
    desc: Run all tests with cleanup (unit + integration)
    deps: [docker:clean]
    cmds:
      - defer: task docker:clean
      - echo "=== Unit Tests ==="
      - go test -short ./...
      - echo "=== Integration Tests (with testcontainers) ==="
      - go test -race ./... -count=1 -timeout 180s
      - echo "=== All tests completed ==="

  #----------------------------------------------------------------------------
  # Quality
  #----------------------------------------------------------------------------
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  check:
    desc: Run all checks (lint, test, build)
    cmds:
      - task: lint
      - task: test:race
      - task: build

  #----------------------------------------------------------------------------
  # Development
  #----------------------------------------------------------------------------
  dev:
    desc: Run in development mode
    cmds:
      - go run . serve

  #----------------------------------------------------------------------------
  # Cleanup
  #----------------------------------------------------------------------------
  clean:
    desc: Remove generated files and binaries
    cmds:
      - rm -f koopa
      - rm -f coverage.out coverage.html

  docker:clean:
    desc: Clean up Docker testcontainers and networks
    cmds:
      - echo "=== Cleaning Docker testcontainers ==="
      - docker ps -aq --filter "label=org.testcontainers=true" | xargs -r docker rm -f 2>/dev/null || true
      - docker ps -aq --filter "ancestor=postgres" --filter "status=exited" | xargs -r docker rm -f 2>/dev/null || true
      - docker ps -aq --filter "ancestor=postgres" --filter "status=created" | xargs -r docker rm -f 2>/dev/null || true
      - echo "=== Cleaning Docker networks ==="
      - docker network ls --filter "name=testcontainers" -q | xargs -r docker network rm 2>/dev/null || true
      - docker network prune -f 2>/dev/null || true
      - echo "=== Docker cleanup complete ==="
