// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/firebase/genkit/go/ai"
	"github.com/firebase/genkit/go/genkit"
	"github.com/firebase/genkit/go/plugins/googlegenai"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/koopa0/koopa/internal/config"
	"github.com/koopa0/koopa/internal/knowledge"
)

// Injectors from wire.go:

// InitializeApp is the Wire injector function.
// Wire will automatically generate the implementation of this function.
func InitializeApp(ctx context.Context, cfg *config.Config) (*App, func(), error) {
	genkit := provideGenkit(ctx)
	embedder := provideEmbedder(genkit, cfg)
	pool, cleanup, err := provideDBPool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	store := provideKnowledgeStore(pool, embedder)
	app, err := newApp(cfg, ctx, genkit, embedder, pool, store)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// providerSet contains all providers.
var providerSet = wire.NewSet(

	provideGenkit,
	provideEmbedder,
	provideDBPool,
	provideKnowledgeStore,

	newApp,
)

// provideGenkit initializes Genkit with Google AI plugin.
func provideGenkit(ctx context.Context) *genkit.Genkit {
	return genkit.Init(ctx, genkit.WithPlugins(&googlegenai.GoogleAI{}), genkit.WithPromptDir("./prompts"))
}

// provideEmbedder creates an embedder instance.
func provideEmbedder(g *genkit.Genkit, cfg *config.Config) ai.Embedder {
	return googlegenai.GoogleAIEmbedder(g, cfg.EmbedderModel)
}

// provideDBPool creates a PostgreSQL connection pool.
func provideDBPool(ctx context.Context, cfg *config.Config) (*pgxpool.Pool, func(), error) {
	pool, err := pgxpool.New(ctx, cfg.PostgresConnectionString())
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		pool.Close()
	}

	return pool, cleanup, nil
}

// provideKnowledgeStore creates a knowledge store instance.
func provideKnowledgeStore(pool *pgxpool.Pool, embedder ai.Embedder) *knowledge.Store {
	return knowledge.New(pool, embedder, nil)
}

// newApp constructs an App instance.
// Wire automatically injects all dependencies.
func newApp(
	cfg *config.Config,
	ctx context.Context,
	g *genkit.Genkit,
	embedder ai.Embedder,
	pool *pgxpool.Pool, knowledge2 *knowledge.Store,
) (*App, error) {

	appCtx, cancel := context.WithCancel(ctx)

	app := &App{
		Config:    cfg,
		ctx:       appCtx,
		cancel:    cancel,
		Genkit:    g,
		Embedder:  embedder,
		DBPool:    pool,
		Knowledge: knowledge2,
	}

	return app, nil
}
