import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
  input,
  computed,
  OnInit,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { Location, DatePipe } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import {
  LucideAngularModule,
  ArrowLeft,
  Calendar,
  Tag,
} from 'lucide-angular';
import { TilService } from '../../core/services/til.service';
import { MarkdownService } from '../../core/services/markdown.service';
import { SeoService } from '../../core/services/seo/seo.service';
import { fadeInUp } from '../../shared/animations/fade-in.animation';
import type { ApiContent } from '../../core/models';

@Component({
  selector: 'app-til-detail',
  standalone: true,
  imports: [RouterLink, DatePipe, LucideAngularModule],
  templateUrl: './til-detail.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [fadeInUp],
  host: { '[@fadeInUp]': '' },
})
export class TilDetailComponent implements OnInit {
  /** Route param: til/:slug */
  readonly slug = input<string>();

  private readonly location = inject(Location);
  private readonly tilService = inject(TilService);
  private readonly markdownService = inject(MarkdownService);
  private readonly sanitizer = inject(DomSanitizer);
  private readonly seoService = inject(SeoService);

  protected readonly til = signal<ApiContent | null>(null);
  protected readonly isLoading = signal(true);
  protected readonly error = signal<string | null>(null);

  // SECURITY_REVIEW: Content generated by MarkdownService, not user-injectable
  protected readonly parsedContent = computed<SafeHtml>(() => {
    const t = this.til();
    if (!t) {
      return '';
    }
    // Strip leading h1 — title is already in the header section
    const body = t.body.replace(/^#\s+.+\n+/, '');
    const html = this.markdownService.parse(body);
    return this.sanitizer.bypassSecurityTrustHtml(html);
  });

  protected readonly ArrowLeftIcon = ArrowLeft;
  protected readonly CalendarIcon = Calendar;
  protected readonly TagIcon = Tag;

  ngOnInit(): void {
    const slugValue = this.slug();
    if (slugValue) {
      this.loadTil(slugValue);
    } else {
      this.error.set('TIL entry not found');
      this.isLoading.set(false);
    }
  }

  private loadTil(slug: string): void {
    this.tilService.getBySlug(slug).subscribe({
      next: (til) => {
        this.til.set(til);
        this.isLoading.set(false);
        this.seoService.updateMeta({
          title: til.title,
          description: til.excerpt || til.body.slice(0, 160),
          ogUrl: `https://koopa0.dev/til/${til.slug}`,
          ogType: 'article',
        });
      },
      error: () => {
        this.error.set('Failed to load TIL entry');
        this.isLoading.set(false);
      },
    });
  }

  protected goBack(): void {
    this.location.back();
  }
}
