import { Article, ArticleListItem, ArticleStatus, Tag } from '../models';

export const MOCK_TAGS: Tag[] = [
  {
    id: '1',
    name: 'Angular',
    slug: 'angular',
    description: 'Angular Framework',
    color: '#DD0031',
    articleCount: 12,
  },
  {
    id: '2',
    name: 'TypeScript',
    slug: 'typescript',
    description: 'TypeScript Language',
    color: '#3178C6',
    articleCount: 15,
  },
  {
    id: '3',
    name: 'Golang',
    slug: 'golang',
    description: 'Go Programming Language',
    color: '#00ADD8',
    articleCount: 8,
  },
  {
    id: '4',
    name: 'Rust',
    slug: 'rust',
    description: 'Rust Programming Language',
    color: '#CE422B',
    articleCount: 6,
  },
  {
    id: '5',
    name: 'Flutter',
    slug: 'flutter',
    description: 'Flutter Framework',
    color: '#02569B',
    articleCount: 4,
  },
  {
    id: '6',
    name: 'PostgreSQL',
    slug: 'postgresql',
    description: 'PostgreSQL Database',
    color: '#336791',
    articleCount: 5,
  },
  {
    id: '7',
    name: 'AI',
    slug: 'ai',
    description: 'Artificial Intelligence',
    color: '#FF6B6B',
    articleCount: 7,
  },
  {
    id: '8',
    name: 'Web Development',
    slug: 'web-development',
    description: 'Web Development',
    color: '#4ECDC4',
    articleCount: 20,
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Angular Signals: 完整指南與最佳實踐',
    slug: 'angular-signals-complete-guide',
    excerpt:
      '深入探討 Angular 20+ 中的 Signal 響應式編程，包含實戰範例和效能優化技巧。從基礎概念到進階應用，掌握現代 Angular 開發的核心。',
    content: '',
    coverImage: '/assets/images/angular-signals.jpg',
    tags: ['Angular', 'TypeScript', 'Web Development'],
    publishedAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
    readingTime: 12,
    viewCount: 1250,
    status: ArticleStatus.PUBLISHED,
    seoDescription:
      'Angular 20+ Signals 完整指南，包含基礎用法、最佳實踐和效能優化技巧',
    seoKeywords: ['Angular', 'Signals', 'TypeScript', '響應式編程'],
    seriesId: 'modern-frontend',
    seriesOrder: 1,
  },
  {
    id: '2',
    title: 'Golang 併發編程：Goroutines 與 Channels 深度解析',
    slug: 'golang-concurrency-goroutines-channels',
    excerpt:
      '探索 Go 語言強大的併發模型，從 goroutines 的基本概念到 channels 的高級用法，打造高性能的併發應用程序。',
    content: '',
    coverImage: '/assets/images/golang-concurrency.jpg',
    tags: ['Golang'],
    publishedAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-11-28'),
    readingTime: 15,
    viewCount: 980,
    status: ArticleStatus.PUBLISHED,
    seoDescription:
      'Golang 併發編程完整指南，深入解析 goroutines 和 channels 的使用',
    seoKeywords: ['Golang', 'Goroutines', 'Channels', '併發編程'],
  },
  {
    id: '3',
    title: 'Rust 所有權系統：記憶體安全的革命性方法',
    slug: 'rust-ownership-memory-safety',
    excerpt:
      'Rust 的所有權系統如何在不使用垃圾回收器的情況下保證記憶體安全？深入了解借用、生命週期和所有權轉移的核心概念。',
    content: '',
    coverImage: '/assets/images/rust-ownership.jpg',
    tags: ['Rust'],
    publishedAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-11-25'),
    readingTime: 18,
    viewCount: 756,
    status: ArticleStatus.PUBLISHED,
  },
  {
    id: '4',
    title: 'Flutter 狀態管理：Riverpod vs Bloc 完整比較',
    slug: 'flutter-state-management-riverpod-bloc',
    excerpt:
      '深度比較 Flutter 兩大主流狀態管理方案：Riverpod 和 Bloc。從架構設計到實際應用，幫你選擇最適合的解決方案。',
    content: '',
    coverImage: '/assets/images/flutter-state-management.jpg',
    tags: ['Flutter'],
    publishedAt: new Date('2024-11-22'),
    updatedAt: new Date('2024-11-22'),
    readingTime: 14,
    viewCount: 623,
    status: ArticleStatus.PUBLISHED,
    seriesId: 'modern-frontend',
    seriesOrder: 2,
  },
  {
    id: '5',
    title: 'PostgreSQL 效能優化：索引策略與查詢調優',
    slug: 'postgresql-performance-optimization',
    excerpt:
      'PostgreSQL 效能優化的完整指南，包含索引設計、查詢分析、配置調優等實戰技巧，讓你的資料庫效能飆升。',
    content: '',
    coverImage: '/assets/images/postgresql-optimization.jpg',
    tags: ['PostgreSQL'],
    publishedAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-20'),
    readingTime: 16,
    viewCount: 892,
    status: ArticleStatus.PUBLISHED,
  },
  {
    id: '6',
    title: 'AI 輔助程式開發：ChatGPT 與 GitHub Copilot 實戰指南',
    slug: 'ai-assisted-programming-guide',
    excerpt:
      'AI 工具如何革命性地改變程式開發流程？深入探討 ChatGPT、GitHub Copilot 等 AI 工具的實際應用技巧。',
    content: '',
    tags: ['AI', 'Web Development'],
    publishedAt: new Date('2024-11-18'),
    updatedAt: new Date('2024-11-18'),
    readingTime: 10,
    viewCount: 1100,
    status: ArticleStatus.PUBLISHED,
  },
];

export const MOCK_ARTICLE_LIST_ITEMS: ArticleListItem[] = MOCK_ARTICLES.map(
  (article) => ({
    id: article.id,
    title: article.title,
    slug: article.slug,
    excerpt: article.excerpt,
    coverImage: article.coverImage,
    tags: article.tags,
    publishedAt: article.publishedAt,
    readingTime: article.readingTime,
    viewCount: article.viewCount,
    seriesId: article.seriesId,
    seriesOrder: article.seriesOrder,
  }),
);
