// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one

INSERT INTO session_artifacts (
    session_id,
    message_id,
    type,
    language,
    title,
    content,
    sequence_number
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE((SELECT MAX(sequence_number) + 1 FROM session_artifacts WHERE session_id = $1), 1)
)
RETURNING id, session_id, message_id, type, language, title, content, version, sequence_number, created_at, updated_at
`

type CreateArtifactParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	MessageID pgtype.UUID `json:"message_id"`
	Type      string      `json:"type"`
	Language  *string     `json:"language"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
}

// Artifact queries for sqlc
// Canvas Mode Comprehensive Fixes
// Create a new artifact for canvas panel (autosave)
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (SessionArtifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.SessionID,
		arg.MessageID,
		arg.Type,
		arg.Language,
		arg.Title,
		arg.Content,
	)
	var i SessionArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Type,
		&i.Language,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.SequenceNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM session_artifacts
WHERE id = $1
`

// Delete an artifact
func (q *Queries) DeleteArtifact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const getLatestArtifact = `-- name: GetLatestArtifact :one
SELECT id, session_id, message_id, type, language, title, content, version, sequence_number, created_at, updated_at
FROM session_artifacts
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Get the most recent artifact for a session (canvas panel display)
func (q *Queries) GetLatestArtifact(ctx context.Context, sessionID pgtype.UUID) (SessionArtifact, error) {
	row := q.db.QueryRow(ctx, getLatestArtifact, sessionID)
	var i SessionArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Type,
		&i.Language,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.SequenceNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsBySession = `-- name: ListArtifactsBySession :many
SELECT id, session_id, message_id, type, language, title, content, version, sequence_number, created_at, updated_at
FROM session_artifacts
WHERE session_id = $1
ORDER BY sequence_number DESC
LIMIT $3
OFFSET $2
`

type ListArtifactsBySessionParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ResultOffset int32       `json:"result_offset"`
	ResultLimit  int32       `json:"result_limit"`
}

// List artifacts for a session, newest first
func (q *Queries) ListArtifactsBySession(ctx context.Context, arg ListArtifactsBySessionParams) ([]SessionArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsBySession, arg.SessionID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionArtifact{}
	for rows.Next() {
		var i SessionArtifact
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.Type,
			&i.Language,
			&i.Title,
			&i.Content,
			&i.Version,
			&i.SequenceNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactContent = `-- name: UpdateArtifactContent :exec
UPDATE session_artifacts
SET content = $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1
`

type UpdateArtifactContentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

// Update artifact content (for future interactive editing)
func (q *Queries) UpdateArtifactContent(ctx context.Context, arg UpdateArtifactContentParams) error {
	_, err := q.db.Exec(ctx, updateArtifactContent, arg.ID, arg.Content)
	return err
}
