// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO session_messages (session_id, role, content, sequence_number)
VALUES ($1, $2, $3, $4)
`

type AddMessageParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	Role           string      `json:"role"`
	Content        []byte      `json:"content"`
	SequenceNumber int32       `json:"sequence_number"`
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.SequenceNumber,
	)
	return err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (title, model_name, system_prompt)
VALUES ($1, $2, $3)
RETURNING id, title, created_at, updated_at, model_name, system_prompt, message_count
`

type CreateSessionParams struct {
	Title        *string `json:"title"`
	ModelName    *string `json:"model_name"`
	SystemPrompt *string `json:"system_prompt"`
}

// Sessions queries for sqlc
// Generated code will be in internal/sqlc/sessions.sql.go
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Title, arg.ModelName, arg.SystemPrompt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelName,
		&i.SystemPrompt,
		&i.MessageCount,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getMaxSequenceNumber = `-- name: GetMaxSequenceNumber :one
SELECT COALESCE(MAX(sequence_number), 0) AS max_seq
FROM session_messages
WHERE session_id = $1
`

func (q *Queries) GetMaxSequenceNumber(ctx context.Context, sessionID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceNumber, sessionID)
	var max_seq interface{}
	err := row.Scan(&max_seq)
	return max_seq, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, session_id, role, content, sequence_number, created_at
FROM session_messages
WHERE session_id = $1
ORDER BY sequence_number ASC
LIMIT $3
OFFSET $2
`

type GetMessagesParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ResultOffset int         `json:"result_offset"`
	ResultLimit  int         `json:"result_limit"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]SessionMessage, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.SessionID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMessage{}
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.SequenceNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, title, created_at, updated_at, model_name, system_prompt, message_count
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelName,
		&i.SystemPrompt,
		&i.MessageCount,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, title, created_at, updated_at, model_name, system_prompt, message_count
FROM sessions
ORDER BY updated_at DESC
LIMIT $2
OFFSET $1
`

type ListSessionsParams struct {
	ResultOffset int `json:"result_offset"`
	ResultLimit  int `json:"result_limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelName,
			&i.SystemPrompt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionUpdatedAt = `-- name: UpdateSessionUpdatedAt :exec
UPDATE sessions
SET updated_at = NOW(),
    message_count = $1
WHERE id = $2
`

type UpdateSessionUpdatedAtParams struct {
	MessageCount *int32      `json:"message_count"`
	SessionID    pgtype.UUID `json:"session_id"`
}

func (q *Queries) UpdateSessionUpdatedAt(ctx context.Context, arg UpdateSessionUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, updateSessionUpdatedAt, arg.MessageCount, arg.SessionID)
	return err
}
