// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages (session_id, role, content, sequence_number)
VALUES ($1, $2, $3, $4)
`

type AddMessageParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	Role           string    `json:"role"`
	Content        []byte    `json:"content"`
	SequenceNumber int32     `json:"sequence_number"`
}

// Add a message to a session
func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.SequenceNumber,
	)
	return err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (title)
VALUES ($1)
RETURNING id, title, created_at, updated_at
`

// Sessions and messages queries for sqlc
// Generated code will be in internal/sqlc/sessions.sql.go
func (q *Queries) CreateSession(ctx context.Context, title *string) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, title)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const maxSequenceNumber = `-- name: MaxSequenceNumber :one
SELECT COALESCE(MAX(sequence_number), 0)::integer AS max_seq
FROM messages
WHERE session_id = $1
`

// MaxSequenceNumber returns the max sequence number for a session (returns 0 if no messages).
func (q *Queries) MaxSequenceNumber(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxSequenceNumber, sessionID)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const lockSession = `-- name: LockSession :one
SELECT id FROM sessions WHERE id = $1 FOR UPDATE
`

// Locks the session row to prevent concurrent modifications
func (q *Queries) LockSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	err := row.Scan(&id)
	return id, err
}

const messages = `-- name: Messages :many
SELECT id, session_id, role, content, sequence_number, created_at
FROM messages
WHERE session_id = $1
ORDER BY sequence_number ASC
LIMIT $3
OFFSET $2
`

type MessagesParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

// Get all messages for a session ordered by sequence
func (q *Queries) Messages(ctx context.Context, arg MessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messages, arg.SessionID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.SequenceNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const session = `-- name: Session :one
SELECT id, title, created_at, updated_at
FROM sessions
WHERE id = $1
`

func (q *Queries) Session(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, session, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessions = `-- name: Sessions :many
SELECT id, title, created_at, updated_at
FROM sessions
ORDER BY updated_at DESC
LIMIT $2
OFFSET $1
`

type SessionsParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) Sessions(ctx context.Context, arg SessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessions, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET title = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateSessionTitleParams struct {
	Title     *string   `json:"title"`
	SessionID uuid.UUID `json:"session_id"`
}

// Update session title (for auto-generation from first message or user edit)
func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.Exec(ctx, updateSessionTitle, arg.Title, arg.SessionID)
	return err
}

const updateSessionUpdatedAt = `-- name: UpdateSessionUpdatedAt :exec
UPDATE sessions
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionUpdatedAt(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionUpdatedAt, sessionID)
	return err
}
