// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO message (session_id, role, content, sequence_number)
VALUES ($1, $2, $3, $4)
`

type AddMessageParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	Role           string    `json:"role"`
	Content        []byte    `json:"content"`
	SequenceNumber int32     `json:"sequence_number"`
}

// Add a message to a session
func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.SequenceNumber,
	)
	return err
}

const addMessageWithID = `-- name: AddMessageWithID :one
INSERT INTO message (id, session_id, role, content, status, sequence_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, role, content, sequence_number, created_at, status, updated_at
`

type AddMessageWithIDParams struct {
	ID             uuid.UUID `json:"id"`
	SessionID      uuid.UUID `json:"session_id"`
	Role           string    `json:"role"`
	Content        []byte    `json:"content"`
	Status         string    `json:"status"`
	SequenceNumber int32     `json:"sequence_number"`
}

// Add message with pre-assigned ID and status (for streaming)
func (q *Queries) AddMessageWithID(ctx context.Context, arg AddMessageWithIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, addMessageWithID,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Status,
		arg.SequenceNumber,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.SequenceNumber,
		&i.CreatedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*)::integer AS count
FROM message
WHERE session_id = $1
`

// Count messages in a session
func (q *Queries) CountMessages(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMessages, sessionID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (title, model_name, system_prompt)
VALUES ($1, $2, $3)
RETURNING id, title, created_at, updated_at, model_name, system_prompt, message_count
`

type CreateSessionParams struct {
	Title        *string `json:"title"`
	ModelName    *string `json:"model_name"`
	SystemPrompt *string `json:"system_prompt"`
}

// Sessions queries for sqlc
// Generated code will be in internal/sqlc/sessions.sql.go
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Title, arg.ModelName, arg.SystemPrompt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelName,
		&i.SystemPrompt,
		&i.MessageCount,
	)
	return i, err
}

const deleteMessages = `-- name: DeleteMessages :exec
DELETE FROM message
WHERE session_id = $1
`

// Delete all messages in a session
func (q *Queries) DeleteMessages(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessages, sessionID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getMaxSequenceNumber = `-- name: GetMaxSequenceNumber :one
SELECT COALESCE(MAX(sequence_number), 0)::integer AS max_seq
FROM message
WHERE session_id = $1
`

// Get max sequence number for a session
func (q *Queries) GetMaxSequenceNumber(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceNumber, sessionID)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, session_id, role, content, sequence_number, created_at, status, updated_at
FROM message
WHERE id = $1
`

// Get a single message by ID (for streaming lookup).
func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.SequenceNumber,
		&i.CreatedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, session_id, role, content, sequence_number, created_at, status, updated_at
FROM message
WHERE session_id = $1
ORDER BY sequence_number ASC
LIMIT $3
OFFSET $2
`

type GetMessagesParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

// Get all messages for a session ordered by sequence
func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.SessionID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.SequenceNumber,
			&i.CreatedAt,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, title, created_at, updated_at, model_name, system_prompt, message_count
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelName,
		&i.SystemPrompt,
		&i.MessageCount,
	)
	return i, err
}

const getUserMessageBefore = `-- name: GetUserMessageBefore :one
SELECT content
FROM message
WHERE session_id = $1
  AND role = 'user'
  AND sequence_number < $2
ORDER BY sequence_number DESC
LIMIT 1
`

type GetUserMessageBeforeParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	BeforeSequence int32     `json:"before_sequence"`
}

// Get the user message content immediately before a given sequence number.
// Used by Stream handler to retrieve query without URL parameter.
func (q *Queries) GetUserMessageBefore(ctx context.Context, arg GetUserMessageBeforeParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserMessageBefore, arg.SessionID, arg.BeforeSequence)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, title, created_at, updated_at, model_name, system_prompt, message_count
FROM sessions
ORDER BY updated_at DESC
LIMIT $2
OFFSET $1
`

type ListSessionsParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelName,
			&i.SystemPrompt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsWithMessages = `-- name: ListSessionsWithMessages :many
SELECT id, title, created_at, updated_at, model_name, system_prompt, message_count
FROM sessions
WHERE message_count > 0 OR title IS NOT NULL
ORDER BY updated_at DESC
LIMIT $2
OFFSET $1
`

type ListSessionsWithMessagesParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

// Only list sessions that have messages or titles (not empty sessions)
// This is used for sidebar to hide "New Chat" placeholder sessions
func (q *Queries) ListSessionsWithMessages(ctx context.Context, arg ListSessionsWithMessagesParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsWithMessages, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelName,
			&i.SystemPrompt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT id FROM sessions WHERE id = $1 FOR UPDATE
`

// Locks the session row to prevent concurrent modifications
func (q *Queries) LockSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	err := row.Scan(&id)
	return id, err
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE message
SET content = $2,
    status = 'completed',
    updated_at = NOW()
WHERE id = $1
`

type UpdateMessageContentParams struct {
	ID      uuid.UUID `json:"id"`
	Content []byte    `json:"content"`
}

// Update message content and mark as completed
func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.Exec(ctx, updateMessageContent, arg.ID, arg.Content)
	return err
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE message
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMessageStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Update message status (streaming/completed/failed)
func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus, arg.ID, arg.Status)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET title = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateSessionTitleParams struct {
	Title     *string   `json:"title"`
	SessionID uuid.UUID `json:"session_id"`
}

// Update session title (for auto-generation from first message or user edit)
func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.Exec(ctx, updateSessionTitle, arg.Title, arg.SessionID)
	return err
}

const updateSessionUpdatedAt = `-- name: UpdateSessionUpdatedAt :exec
UPDATE sessions
SET updated_at = NOW(),
    message_count = $1
WHERE id = $2
`

type UpdateSessionUpdatedAtParams struct {
	MessageCount *int32    `json:"message_count"`
	SessionID    uuid.UUID `json:"session_id"`
}

func (q *Queries) UpdateSessionUpdatedAt(ctx context.Context, arg UpdateSessionUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, updateSessionUpdatedAt, arg.MessageCount, arg.SessionID)
	return err
}
