package ui

// IO defines the contract for user input and output.
// It follows the semantics of standard library interfaces like io.Reader and fmt.Scanner.
type IO interface {
	// Output methods (similar to fmt package)
	Print(a ...any)
	Println(a ...any)
	Printf(format string, a ...any)

	// Input methods (similar to bufio.Scanner)
	// Scan advances the scanner to the next token (line).
	Scan() bool
	// Text returns the most recent token generated by a call to Scan.
	Text() string

	// Interaction methods
	// Confirm prompts the user for a yes/no confirmation.
	Confirm(prompt string) (bool, error)

	// Stream displays streaming content (e.g., from AI generation).
	Stream(content string)
}
