apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-critical
    receivers:
      - uid: telegram-critical-1
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "-5209749160"
          parse_mode: HTML
        disableResolveMessage: false

  - orgId: 1
    name: telegram-warning
    receivers:
      - uid: telegram-warning-1
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "-5000758856"
          parse_mode: HTML
        disableResolveMessage: false
