import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
  computed,
  OnInit,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location, DatePipe } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import {
  LucideAngularModule,
  ArrowLeft,
  Calendar,
  Clock,
} from 'lucide-angular';
import { BuildLogService } from '../../core/services/build-log.service';
import { MarkdownService } from '../../core/services/markdown.service';
import { SeoService } from '../../core/services/seo/seo.service';
import { fadeInUp } from '../../shared/animations/fade-in.animation';
import type { ApiContent } from '../../core/models';
import { TableOfContentsComponent } from '../../shared/table-of-contents/table-of-contents.component';

@Component({
  selector: 'app-build-log-detail',
  standalone: true,
  imports: [DatePipe, LucideAngularModule, TableOfContentsComponent],
  templateUrl: './build-log-detail.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [fadeInUp],
  host: { '[@fadeInUp]': '' },
})
export class BuildLogDetailComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly location = inject(Location);
  private readonly buildLogService = inject(BuildLogService);
  private readonly markdownService = inject(MarkdownService);
  private readonly sanitizer = inject(DomSanitizer);
  private readonly seoService = inject(SeoService);

  protected readonly buildLog = signal<ApiContent | null>(null);
  protected readonly isLoading = signal(true);
  protected readonly error = signal<string | null>(null);

  protected readonly rawHtml = computed(() => {
    const bl = this.buildLog();
    if (!bl) {
      return '';
    }
    return this.markdownService.parse(bl.body);
  });

  // SECURITY_REVIEW: Same as article-detail — content generated by MarkdownService, not user-injectable
  protected readonly parsedContent = computed<SafeHtml>(() => {
    const html = this.rawHtml();
    return html ? this.sanitizer.bypassSecurityTrustHtml(html) : '';
  });

  protected readonly ArrowLeftIcon = ArrowLeft;
  protected readonly CalendarIcon = Calendar;
  protected readonly ClockIcon = Clock;

  ngOnInit(): void {
    const slug = this.route.snapshot.paramMap.get('slug');
    if (slug) {
      this.loadBuildLog(slug);
    } else {
      this.error.set('Build log not found');
      this.isLoading.set(false);
    }
  }

  private loadBuildLog(slug: string): void {
    this.buildLogService.getBySlug(slug).subscribe({
      next: (bl) => {
        this.buildLog.set(bl);
        this.isLoading.set(false);
        this.seoService.updateMeta({
          title: bl.title,
          description: bl.excerpt,
          ogUrl: `https://koopa0.dev/build-logs/${bl.slug}`,
          ogType: 'article',
        });
      },
      error: () => {
        this.error.set('Failed to load build log');
        this.isLoading.set(false);
      },
    });
  }

  protected goBack(): void {
    this.location.back();
  }
}
