import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
  input,
  computed,
  OnInit,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { Location, DatePipe } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import {
  LucideAngularModule,
  ArrowLeft,
  Calendar,
} from 'lucide-angular';
import { NoteService } from '../../core/services/note.service';
import { MarkdownService } from '../../core/services/markdown.service';
import { SeoService } from '../../core/services/seo/seo.service';
import { fadeInUp } from '../../shared/animations/fade-in.animation';
import type { ApiContent } from '../../core/models';

@Component({
  selector: 'app-note-detail',
  standalone: true,
  imports: [RouterLink, DatePipe, LucideAngularModule],
  templateUrl: './note-detail.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [fadeInUp],
  host: { '[@fadeInUp]': '' },
})
export class NoteDetailComponent implements OnInit {
  /** Route param: notes/:slug */
  readonly slug = input<string>();

  private readonly location = inject(Location);
  private readonly noteService = inject(NoteService);
  private readonly markdownService = inject(MarkdownService);
  private readonly sanitizer = inject(DomSanitizer);
  private readonly seoService = inject(SeoService);

  protected readonly note = signal<ApiContent | null>(null);
  protected readonly isLoading = signal(true);
  protected readonly error = signal<string | null>(null);

  // SECURITY_REVIEW: Content generated by MarkdownService, not user-injectable
  protected readonly parsedContent = computed<SafeHtml>(() => {
    const n = this.note();
    if (!n) {
      return '';
    }
    // Strip leading h1 — title is already in the header section
    const body = n.body.replace(/^#\s+.+\n+/, '');
    const html = this.markdownService.parse(body);
    return this.sanitizer.bypassSecurityTrustHtml(html);
  });

  protected readonly ArrowLeftIcon = ArrowLeft;
  protected readonly CalendarIcon = Calendar;

  ngOnInit(): void {
    const slugValue = this.slug();
    if (slugValue) {
      this.loadNote(slugValue);
    } else {
      this.error.set('Note not found');
      this.isLoading.set(false);
    }
  }

  private loadNote(slug: string): void {
    this.noteService.getBySlug(slug).subscribe({
      next: (note) => {
        this.note.set(note);
        this.isLoading.set(false);
        this.seoService.updateMeta({
          title: note.title,
          description: note.excerpt || note.body.slice(0, 160),
          ogUrl: `https://koopa0.dev/notes/${note.slug}`,
          ogType: 'article',
        });
      },
      error: () => {
        this.error.set('Failed to load note');
        this.isLoading.set(false);
      },
    });
  }

  protected goBack(): void {
    this.location.back();
  }
}
