// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type CollectedStatus string

const (
	CollectedStatusUnread  CollectedStatus = "unread"
	CollectedStatusRead    CollectedStatus = "read"
	CollectedStatusCurated CollectedStatus = "curated"
	CollectedStatusIgnored CollectedStatus = "ignored"
)

func (e *CollectedStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectedStatus(s)
	case string:
		*e = CollectedStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectedStatus: %T", src)
	}
	return nil
}

type NullCollectedStatus struct {
	CollectedStatus CollectedStatus `json:"collected_status"`
	Valid           bool            `json:"valid"` // Valid is true if CollectedStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectedStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CollectedStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectedStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectedStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectedStatus), nil
}

type ContentStatus string

const (
	ContentStatusDraft     ContentStatus = "draft"
	ContentStatusReview    ContentStatus = "review"
	ContentStatusPublished ContentStatus = "published"
	ContentStatusArchived  ContentStatus = "archived"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus `json:"content_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

type ContentType string

const (
	ContentTypeArticle  ContentType = "article"
	ContentTypeEssay    ContentType = "essay"
	ContentTypeBuildLog ContentType = "build-log"
	ContentTypeTil      ContentType = "til"
	ContentTypeNote     ContentType = "note"
	ContentTypeBookmark ContentType = "bookmark"
	ContentTypeDigest   ContentType = "digest"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type FlowStatus string

const (
	FlowStatusPending   FlowStatus = "pending"
	FlowStatusRunning   FlowStatus = "running"
	FlowStatusCompleted FlowStatus = "completed"
	FlowStatusFailed    FlowStatus = "failed"
)

func (e *FlowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlowStatus(s)
	case string:
		*e = FlowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlowStatus: %T", src)
	}
	return nil
}

type NullFlowStatus struct {
	FlowStatus FlowStatus `json:"flow_status"`
	Valid      bool       `json:"valid"` // Valid is true if FlowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlowStatus), nil
}

type GoalStatus string

const (
	GoalStatusNotStarted GoalStatus = "not-started"
	GoalStatusInProgress GoalStatus = "in-progress"
	GoalStatusDone       GoalStatus = "done"
	GoalStatusAbandoned  GoalStatus = "abandoned"
)

func (e *GoalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoalStatus(s)
	case string:
		*e = GoalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GoalStatus: %T", src)
	}
	return nil
}

type NullGoalStatus struct {
	GoalStatus GoalStatus `json:"goal_status"`
	Valid      bool       `json:"valid"` // Valid is true if GoalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GoalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoalStatus), nil
}

type ProjectStatus string

const (
	ProjectStatusPlanned    ProjectStatus = "planned"
	ProjectStatusInProgress ProjectStatus = "in-progress"
	ProjectStatusOnHold     ProjectStatus = "on-hold"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusMaintained ProjectStatus = "maintained"
	ProjectStatusArchived   ProjectStatus = "archived"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus `json:"project_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

type ReviewLevel string

const (
	ReviewLevelAuto     ReviewLevel = "auto"
	ReviewLevelLight    ReviewLevel = "light"
	ReviewLevelStandard ReviewLevel = "standard"
	ReviewLevelStrict   ReviewLevel = "strict"
)

func (e *ReviewLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewLevel(s)
	case string:
		*e = ReviewLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewLevel: %T", src)
	}
	return nil
}

type NullReviewLevel struct {
	ReviewLevel ReviewLevel `json:"review_level"`
	Valid       bool        `json:"valid"` // Valid is true if ReviewLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewLevel), nil
}

type ReviewStatus string

const (
	ReviewStatusPending  ReviewStatus = "pending"
	ReviewStatusApproved ReviewStatus = "approved"
	ReviewStatusRejected ReviewStatus = "rejected"
	ReviewStatusEdited   ReviewStatus = "edited"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type SourceType string

const (
	SourceTypeObsidian    SourceType = "obsidian"
	SourceTypeNotion      SourceType = "notion"
	SourceTypeAiGenerated SourceType = "ai-generated"
	SourceTypeExternal    SourceType = "external"
	SourceTypeManual      SourceType = "manual"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType `json:"source_type"`
	Valid      bool       `json:"valid"` // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type CollectedDatum struct {
	ID               uuid.UUID       `json:"id"`
	SourceUrl        string          `json:"source_url"`
	SourceName       string          `json:"source_name"`
	Title            string          `json:"title"`
	OriginalContent  *string         `json:"original_content"`
	AiSummary        *string         `json:"ai_summary"`
	RelevanceScore   float32         `json:"relevance_score"`
	Topics           []string        `json:"topics"`
	Status           CollectedStatus `json:"status"`
	CuratedContentID *uuid.UUID      `json:"curated_content_id"`
	CollectedAt      time.Time       `json:"collected_at"`
	UrlHash          string          `json:"url_hash"`
	AiScore          *int16          `json:"ai_score"`
	AiScoreReason    *string         `json:"ai_score_reason"`
	AiSummaryZh      *string         `json:"ai_summary_zh"`
	AiTitleZh        *string         `json:"ai_title_zh"`
	UserFeedback     *string         `json:"user_feedback"`
	FeedbackAt       *time.Time      `json:"feedback_at"`
	FeedID           *uuid.UUID      `json:"feed_id"`
}

type Content struct {
	ID           uuid.UUID           `json:"id"`
	Slug         string              `json:"slug"`
	Title        string              `json:"title"`
	Body         string              `json:"body"`
	Excerpt      string              `json:"excerpt"`
	Type         ContentType         `json:"type"`
	Status       ContentStatus       `json:"status"`
	Tags         []string            `json:"tags"`
	Source       *string             `json:"source"`
	SourceType   NullSourceType      `json:"source_type"`
	SeriesID     *string             `json:"series_id"`
	SeriesOrder  *int32              `json:"series_order"`
	ReviewLevel  ReviewLevel         `json:"review_level"`
	AiMetadata   json.RawMessage     `json:"ai_metadata"`
	ReadingTime  int32               `json:"reading_time"`
	CoverImage   *string             `json:"cover_image"`
	PublishedAt  *time.Time          `json:"published_at"`
	CreatedAt    time.Time           `json:"created_at"`
	UpdatedAt    time.Time           `json:"updated_at"`
	Embedding    *pgvector_go.Vector `json:"embedding"`
	SearchVector interface{}         `json:"search_vector"`
}

type ContentTopic struct {
	ContentID uuid.UUID `json:"content_id"`
	TopicID   uuid.UUID `json:"topic_id"`
}

type Feed struct {
	ID                  uuid.UUID  `json:"id"`
	Url                 string     `json:"url"`
	Name                string     `json:"name"`
	Schedule            string     `json:"schedule"`
	Topics              []string   `json:"topics"`
	Enabled             bool       `json:"enabled"`
	Etag                string     `json:"etag"`
	LastModified        string     `json:"last_modified"`
	LastFetchedAt       *time.Time `json:"last_fetched_at"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
	LastError           string     `json:"last_error"`
	DisabledReason      string     `json:"disabled_reason"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type FlowRun struct {
	ID          uuid.UUID       `json:"id"`
	FlowName    string          `json:"flow_name"`
	ContentID   *uuid.UUID      `json:"content_id"`
	Input       []byte          `json:"input"`
	Output      json.RawMessage `json:"output"`
	Status      FlowStatus      `json:"status"`
	Error       *string         `json:"error"`
	Attempt     int32           `json:"attempt"`
	MaxAttempts int32           `json:"max_attempts"`
	StartedAt   *time.Time      `json:"started_at"`
	EndedAt     *time.Time      `json:"ended_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Goal struct {
	ID           uuid.UUID  `json:"id"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Status       GoalStatus `json:"status"`
	Area         string     `json:"area"`
	Quarter      string     `json:"quarter"`
	Deadline     *time.Time `json:"deadline"`
	NotionPageID *string    `json:"notion_page_id"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type Project struct {
	ID              uuid.UUID     `json:"id"`
	Slug            string        `json:"slug"`
	Title           string        `json:"title"`
	Description     string        `json:"description"`
	LongDescription *string       `json:"long_description"`
	Role            string        `json:"role"`
	TechStack       []string      `json:"tech_stack"`
	Highlights      []string      `json:"highlights"`
	Problem         *string       `json:"problem"`
	Solution        *string       `json:"solution"`
	Architecture    *string       `json:"architecture"`
	Results         *string       `json:"results"`
	GithubUrl       *string       `json:"github_url"`
	LiveUrl         *string       `json:"live_url"`
	Featured        bool          `json:"featured"`
	SortOrder       int32         `json:"sort_order"`
	Status          ProjectStatus `json:"status"`
	NotionPageID    *string       `json:"notion_page_id"`
	Repo            *string       `json:"repo"`
	Area            string        `json:"area"`
	Deadline        *time.Time    `json:"deadline"`
	LastActivityAt  *time.Time    `json:"last_activity_at"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type ReviewQueue struct {
	ID            uuid.UUID    `json:"id"`
	ContentID     uuid.UUID    `json:"content_id"`
	ReviewLevel   ReviewLevel  `json:"review_level"`
	Status        ReviewStatus `json:"status"`
	ReviewerNotes *string      `json:"reviewer_notes"`
	SubmittedAt   time.Time    `json:"submitted_at"`
	ReviewedAt    *time.Time   `json:"reviewed_at"`
}

type Topic struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Icon        *string   `json:"icon"`
	SortOrder   int32     `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TrackingTopic struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Keywords  []string  `json:"keywords"`
	Sources   []string  `json:"sources"`
	Enabled   bool      `json:"enabled"`
	Schedule  string    `json:"schedule"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
