// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createItem = `-- name: CreateItem :batchone
INSERT INTO daily_plan_items (plan_date, todo_id, selected_by, position, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (plan_date, todo_id) DO UPDATE SET
    selected_by = EXCLUDED.selected_by,
    position = EXCLUDED.position,
    reason = EXCLUDED.reason,
    updated_at = now()
WHERE daily_plan_items.status = 'planned'
RETURNING id, plan_date, todo_id, selected_by, position, reason, status, created_at, updated_at
`

type CreateItemBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateItemParams struct {
	PlanDate   time.Time `json:"plan_date"`
	TodoID     uuid.UUID `json:"todo_id"`
	SelectedBy string    `json:"selected_by"`
	Position   int32     `json:"position"`
	Reason     *string   `json:"reason"`
}

// Insert a daily plan item, or reorder it when it is still 'planned' for the
// date. The ON CONFLICT guard (WHERE status = 'planned') refuses to touch a
// row that already reached a terminal state (done/deferred/dropped): the
// conflicting UPDATE matches no row, so RETURNING is empty and the driver
// yields pgx.ErrNoRows. The store maps that to ErrItemResolved so re-planning
// cannot silently resurrect a resolved item. A fresh insert (no conflict)
// always returns its row, defaulting status to 'planned'.
//
// :batchone (not :one) — every caller inserts a whole plan's worth of items
// in a loop; pgx.Batch pipelines the N executions in one round trip instead
// of N. Each item's ON CONFLICT/RETURNING-empty outcome stays independent
// per index, so the ErrItemResolved-per-item contract above is unchanged.
func (q *Queries) CreateItem(ctx context.Context, arg []CreateItemParams) *CreateItemBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PlanDate,
			a.TodoID,
			a.SelectedBy,
			a.Position,
			a.Reason,
		}
		batch.Queue(createItem, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateItemBatchResults{br, len(arg), false}
}

func (b *CreateItemBatchResults) QueryRow(f func(int, DailyPlanItem, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i DailyPlanItem
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.PlanDate,
			&i.TodoID,
			&i.SelectedBy,
			&i.Position,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateItemBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
