// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type AgentStatus string

const (
	AgentStatusActive  AgentStatus = "active"
	AgentStatusRetired AgentStatus = "retired"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Valid       bool        `json:"valid"` // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type ContentStatus string

const (
	ContentStatusDraft            ContentStatus = "draft"
	ContentStatusReview           ContentStatus = "review"
	ContentStatusChangesRequested ContentStatus = "changes_requested"
	ContentStatusPublished        ContentStatus = "published"
	ContentStatusArchived         ContentStatus = "archived"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus `json:"content_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

type ContentType string

const (
	ContentTypeArticle  ContentType = "article"
	ContentTypeEssay    ContentType = "essay"
	ContentTypeBuildLog ContentType = "build-log"
	ContentTypeTil      ContentType = "til"
	ContentTypeDigest   ContentType = "digest"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type FeedEntryStatus string

const (
	FeedEntryStatusUnread  FeedEntryStatus = "unread"
	FeedEntryStatusRead    FeedEntryStatus = "read"
	FeedEntryStatusCurated FeedEntryStatus = "curated"
	FeedEntryStatusIgnored FeedEntryStatus = "ignored"
)

func (e *FeedEntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedEntryStatus(s)
	case string:
		*e = FeedEntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedEntryStatus: %T", src)
	}
	return nil
}

type NullFeedEntryStatus struct {
	FeedEntryStatus FeedEntryStatus `json:"feed_entry_status"`
	Valid           bool            `json:"valid"` // Valid is true if FeedEntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FeedEntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedEntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedEntryStatus), nil
}

type GoalStatus string

const (
	GoalStatusProposed   GoalStatus = "proposed"
	GoalStatusNotStarted GoalStatus = "not_started"
	GoalStatusInProgress GoalStatus = "in_progress"
	GoalStatusDone       GoalStatus = "done"
	GoalStatusAbandoned  GoalStatus = "abandoned"
	GoalStatusOnHold     GoalStatus = "on_hold"
)

func (e *GoalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoalStatus(s)
	case string:
		*e = GoalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GoalStatus: %T", src)
	}
	return nil
}

type NullGoalStatus struct {
	GoalStatus GoalStatus `json:"goal_status"`
	Valid      bool       `json:"valid"` // Valid is true if GoalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GoalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoalStatus), nil
}

type ProjectStatus string

const (
	ProjectStatusProposed   ProjectStatus = "proposed"
	ProjectStatusPlanned    ProjectStatus = "planned"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusOnHold     ProjectStatus = "on_hold"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusMaintained ProjectStatus = "maintained"
	ProjectStatusArchived   ProjectStatus = "archived"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus `json:"project_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

type TodoState string

const (
	TodoStateInbox      TodoState = "inbox"
	TodoStateTodo       TodoState = "todo"
	TodoStateInProgress TodoState = "in_progress"
	TodoStateDone       TodoState = "done"
	TodoStateSomeday    TodoState = "someday"
	TodoStateArchived   TodoState = "archived"
	TodoStateDismissed  TodoState = "dismissed"
)

func (e *TodoState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoState(s)
	case string:
		*e = TodoState(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoState: %T", src)
	}
	return nil
}

type NullTodoState struct {
	TodoState TodoState `json:"todo_state"`
	Valid     bool      `json:"valid"` // Valid is true if TodoState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoState) Scan(value interface{}) error {
	if value == nil {
		ns.TodoState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoState), nil
}

// Canonical audit log of internal entity state changes. Written by AFTER triggers on covered tables. Application code MUST NOT INSERT into this table directly — the trigger path is the only legitimate writer. RETENTION: indefinite.
type ActivityEvent struct {
	ID uuid.UUID `json:"id"`
	// Which entity domain this event describes. Closed set via CHECK. Used in conjunction with entity_id to identify the specific row that changed.
	EntityType string `json:"entity_type"`
	// UUID of the changed row. Polymorphic — FK integrity is not enforced (would require separate FK per entity_type). entity_title and entity_slug carry the write-time snapshot so read-side consumers (e.g. brief and the admin dashboards) do not need to JOIN live entity tables; a hard-deleted entity_id still has a usable historical record.
	EntityID uuid.UUID `json:"entity_id"`
	// Human-readable title of the entity AT THE TIME of the event. NULL when the trigger cannot resolve one. Survives hard-delete of the referenced entity.
	EntityTitle *string `json:"entity_title"`
	// Slug of the entity AT THE TIME of the event, for slug-addressable types (content, project). NULL otherwise.
	EntitySlug *string `json:"entity_slug"`
	// Closed set of mutation kinds. created = INSERT. state_changed = enum/status transition. completed/published/archived = specific terminal transitions worth distinguishing. updated = generic field change.
	ChangeKind string `json:"change_kind"`
	// Optional project association for project-scoped activity feeds. SET NULL on project deletion.
	ProjectID *uuid.UUID `json:"project_id"`
	// Agent that caused the change. RESTRICT on agent deletion — historical audit must not dangle.
	Actor string `json:"actor"`
	// When the change happened. DEFAULT now() since triggers fire synchronously.
	OccurredAt time.Time `json:"occurred_at"`
	// Change-specific structured data: before/after values, transition reasons, related entity IDs. Schema varies by (entity_type, change_kind) pair.
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

// DB projection of the Go BuiltinAgents() registry. Rows are upserted at startup by agent.SyncToTable. Stores identity only (name, platform, status). Provenance columns (created_by on todos/areas/goals/projects) use ON DELETE RESTRICT so historical records cannot dangle. Removed registry entries transition to status=retired rather than being deleted.
type Agent struct {
	// Unique agent identifier. Used as the caller identity (as: field) in MCP tool calls and as FK target for created_by / assignee / curated_by columns. Format: lowercase, must start with a letter, alphanumeric + hyphens.
	Name string `json:"name"`
	// Human-readable label for admin UI and logs. Non-blank (chk_agent_display_name_not_blank).
	DisplayName string `json:"display_name"`
	// Execution context. Closed set: claude-cowork, claude-code, claude-web, codex, human, system (chk_agent_platform). The system value is reserved for the database-level fallback agent registered by BuiltinAgents — it attributes writes that bypass the Go actor middleware (pg_cron, manual psql ops, bug safety net). Routing decisions are driven by agent registry lookups, not this column.
	Platform string `json:"platform"`
	// Short role description. Empty string = no description.
	Description string `json:"description"`
	// active = currently present in BuiltinAgents(). retired = previously registered but no longer in the Go literal. chk_agent_status_retired ties retired_at to status=retired.
	Status AgentStatus `json:"status"`
	// When this row was last reconciled with BuiltinAgents() by agent.SyncToTable. Updated on every startup sync.
	SyncedAt time.Time `json:"synced_at"`
	// When this agent was retired (removed from BuiltinAgents). NULL while status=active. Set by SyncToTable when the registry entry disappears.
	RetiredAt *time.Time `json:"retired_at"`
	// When the row was first upserted. Useful for onboarding audit.
	CreatedAt time.Time `json:"created_at"`
}

// PARA Areas of Responsibility — ongoing domains requiring sustained attention. Unlike projects (which complete), areas persist indefinitely. Each area has a standard to maintain, not a goal to achieve. Goals and projects reference areas via FK.
type Area struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier (e.g. studio, japanese, literature). Used in filters and API.
	Slug string `json:"slug"`
	// Display name (e.g. 工作室與系統, 日語, 文學閱讀).
	Name string `json:"name"`
	// What this area of responsibility covers and what "maintaining the standard" means.
	Description string `json:"description"`
	// Optional emoji or icon identifier for UI display.
	Icon *string `json:"icon"`
	// Display ordering. Lower = higher priority.
	SortOrder int32 `json:"sort_order"`
	// proposed | active. An agent-proposed area lands in 'proposed' — inert: filtered out of every area selector / resolver, so it cannot become a real goal's parent until activated. The owner activates (→ active) or rejects (DELETE) it in admin triage. Admin/seeded areas are 'active'. Default active so existing and admin inserts need not set it.
	Status string `json:"status"`
	// Provenance. NULL = system/seed origin — areas are seeded in 002 before any agents row exists at startup, so this is NULLABLE with NO default (a NOT NULL or DEFAULT-'human' FK would fail the seed with a foreign_key_violation). An agent name marks an area that agent proposed.
	CreatedBy *string `json:"created_by"`
	// Agent's why-propose-this-now justification, captured on a proposed row and shown to the owner in admin triage to support activate/reject. NULL for admin/seeded rows and acceptable to keep or clear on activation.
	ProposalRationale *string   `json:"proposal_rationale"`
	CreatedAt         time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// First-party publishable knowledge layer. Five content types (article, essay, build-log, til, digest) share one editorial lifecycle: draft → review → published, with a review → changes_requested → review revision loop. The review state is a two-actor handoff — an agent pushes a finished draft into review (propose_content) or the owner drafts in admin; from the admin review queue the human admin publishes OR sends it back (status changes_requested + review_note), and the authoring agent revises (revise_content) back into review. published status and published_at are tied by chk_content_publication; is_public requires published by chk_content_public_requires_published.
type Content struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier. Globally unique. Used in public URLs. Format (chk_content_slug_format): hyphen-separated segments, no whitespace or slash, no leading/trailing/consecutive hyphens. Unicode letters/numbers (incl. CJK) allowed — a 中日文 slug carries UTF-8 in the URL.
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Body    string `json:"body"`
	Excerpt string `json:"excerpt"`
	// Content format: article, essay, build-log, til, digest. All are public-facing first-party content going through the review lifecycle.
	Type ContentType `json:"type"`
	// Lifecycle: draft → review → published | changes_requested; changes_requested → review. review = awaiting a human decision (an agent submits via propose_content, or the owner drafts in admin). changes_requested = the owner sent the draft back for revision, reason in review_note; the authoring agent addresses it with revise_content, which returns the row to review. published = live; archived = soft delete. review → published and review → changes_requested are human-admin only (admin HTTP); the agent tools propose_content/revise_content only ever land a row in review.
	Status ContentStatus `json:"status"`
	// Groups content into a series. Paired with series_order (chk_contents_series).
	SeriesID *string `json:"series_id"`
	// Position within the series. Paired with series_id (chk_contents_series).
	SeriesOrder *int32 `json:"series_order"`
	// AI pipeline metadata (JSONB). Structure: {summary, keywords, quality_score, review_notes}. Set by background AI enrichment.
	AiMetadata json.RawMessage `json:"ai_metadata"`
	// Estimated reading time in minutes. Computed from body word count. Always >= 0.
	ReadingTimeMin int32 `json:"reading_time_min"`
	// Cover image URL or path for content cards and social sharing. NULL = no cover image.
	CoverImage *string `json:"cover_image"`
	// Whether this content is rendered on the public website. Defaults to false (private-by-default). When true, status MUST be 'published' (chk_content_public_requires_published). Publishing flips status, published_at, and is_public together — publishing makes public in this system.
	IsPublic bool `json:"is_public"`
	// Associated project. SET NULL on project deletion — content survives independently.
	ProjectID *uuid.UUID `json:"project_id"`
	// Proposing agent for agent-pushed content (references agents(name), e.g. hermes pushing a finished draft via the propose_content MCP tool). NULL for owner/admin-authored content created through the admin UI. ON DELETE RESTRICT — a registered agent that has proposed content cannot be removed while its proposals exist.
	CreatedBy *string `json:"created_by"`
	// The proposing agent's "why I propose this" note, shown alongside the row in the admin review queue. NULL for admin-authored content (no agent rationale).
	ProposalRationale *string `json:"proposal_rationale"`
	// The owner's revision reason, set when the owner sends a draft back (status → changes_requested) from the admin review queue. The authoring agent reads it via list_content and addresses it with revise_content (which returns the row to review). NULL when the row has never been sent back.
	ReviewNote *string `json:"review_note"`
	// When content was published. NULL = not yet published.
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   time.Time  `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
	// pgvector embedding (1536d) from gemini-embedding-2. See internal/embedder.Dimension — schema + Go must match exactly or pgvector rejects writes.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector for full-text search. Uses 'simple' config (no stemming/language-specific tokenization) for multilingual safety. Weight A = title, C = body (first 10K chars). Semantic search via embedding compensates for tsvector recall limitations.
	SearchVector string `json:"search_vector"`
}

// Junction: content ↔ topic. Many-to-many. Curated knowledge domain categories.
type ContentTopic struct {
	ContentID uuid.UUID `json:"content_id"`
	TopicID   uuid.UUID `json:"topic_id"`
}

// Daily commitment records. Each row represents a todo item selected for a specific day's plan. Lifecycle: planned → done | deferred | dropped. Re-plan replaces only the day's 'planned' rows; terminal rows (done/deferred/dropped) are preserved as history and cannot be re-planned (re-sending one is rejected). Position is unique among 'planned' rows only.
type DailyPlanItem struct {
	ID uuid.UUID `json:"id"`
	// The date this todo was planned for. Combined with todo_id forms a unique constraint — one todo can appear at most once per day.
	PlanDate time.Time `json:"plan_date"`
	// The todo committed to. CASCADE on delete — if the todo is removed, the plan item goes too.
	TodoID uuid.UUID `json:"todo_id"`
	// Which agent added this item to the plan. Typically planner (morning briefing, cron auto-populate) or human (manual selection via MCP tool).
	SelectedBy string `json:"selected_by"`
	// Ordering within a day's plan. 0-based. Semantic: first item = highest priority for today.
	Position int32 `json:"position"`
	// Optional rationale for selecting this todo today. NULL = no specific reason recorded.
	Reason *string `json:"reason"`
	// Lifecycle state. planned = committed for today. done = completed within this day (independent of todos.state for recurring todos). deferred = not done today, carry-over candidate for future planning. dropped = explicitly removed from plan, no intent to carry over.
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Tracks when status last changed. Critical for Weekly Review analysis and cron debug.
	UpdatedAt time.Time `json:"updated_at"`
}

// RSS/Atom feed subscriptions. Fetch pipeline pulls entries on schedule, scores relevance, and surfaces for curation.
type Feed struct {
	ID uuid.UUID `json:"id"`
	// Feed URL (RSS/Atom). Unique — one subscription per URL. Must use http(s) scheme (chk_feed_url_scheme).
	Url  string `json:"url"`
	Name string `json:"name"`
	// Fetch cadence label (hourly | daily | weekly | biweekly | monthly), enforced by chk_feed_schedule. The Go scheduler maps each label to a concrete time interval. NOT a cron expression.
	Schedule string `json:"schedule"`
	Enabled  bool   `json:"enabled"`
	// Feed importance for relevance scoring: high feeds get boosted scores.
	Priority string `json:"priority"`
	// HTTP ETag header from last fetch. NULL = never fetched or server did not return ETag.
	Etag *string `json:"etag"`
	// HTTP Last-Modified header from last fetch. NULL = never fetched or server did not return it.
	LastModified *string `json:"last_modified"`
	// When the feed was last successfully fetched. NULL = never fetched.
	LastFetchedAt *time.Time `json:"last_fetched_at"`
	// Number of consecutive fetch failures. Reset to 0 on success. Auto-disable threshold in Go.
	ConsecutiveFailures int32 `json:"consecutive_failures"`
	// Error message from last failed fetch. NULL = no error (last fetch succeeded or never fetched).
	LastError *string `json:"last_error"`
	// Why this feed was disabled. NULL = not disabled or no reason recorded.
	DisabledReason *string `json:"disabled_reason"`
	// Feed-specific filter rules (JSONB). Structure: {deny_paths, deny_title_patterns, deny_tags}. Empty {} = no filtering.
	FilterConfig json.RawMessage `json:"filter_config"`
	CreatedAt    time.Time       `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// RSS feed items collected by the fetch pipeline. Topic association is read-through feed_topics at query time — changing a feed's topics retroactively changes its entries' visible topics. status=curated requires curated_content_id to be set.
type FeedEntry struct {
	ID uuid.UUID `json:"id"`
	// Original article URL.
	SourceUrl string `json:"source_url"`
	// Article title from the RSS feed. Raw, not cleaned.
	Title string `json:"title"`
	// RSS entry content/summary as delivered by the feed. Empty string when none.
	OriginalContent string `json:"original_content"`
	// Curation lifecycle: unread → read → curated | ignored.
	Status FeedEntryStatus `json:"status"`
	// When curated into first-party content, references the contents row. SET NULL on content deletion.
	CuratedContentID *uuid.UUID `json:"curated_content_id"`
	// When the pipeline first fetched this entry.
	CollectedAt time.Time `json:"collected_at"`
	// SHA256 hex of canonical source_url. Dedup identity. Computed in application code via internal/url before INSERT.
	UrlHash string `json:"url_hash"`
	// Source feed. SET NULL on feed deletion — entries retained for curation.
	FeedID *uuid.UUID `json:"feed_id"`
	// Original publication date from the feed. NULL if not provided.
	PublishedAt *time.Time `json:"published_at"`
}

// Many-to-many: which topics a feed covers.
type FeedTopic struct {
	FeedID  uuid.UUID `json:"feed_id"`
	TopicID uuid.UUID `json:"topic_id"`
}

// Planning objectives — aspirational outcomes with optional deadlines. Each goal may have milestones (progress checkpoints) and projects (execution vehicles). Milestone progress is advisory — goal status is managed manually, not auto-derived.
type Goal struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	// Lifecycle: proposed → not_started → in_progress → done | abandoned | on_hold. proposed = agent-proposed draft, inert — ActiveGoals filters in_progress, so a proposed goal never reaches brief / alignment; the owner activates it to not_started in admin triage or rejects (DELETE, milestones CASCADE). on_hold = paused but not abandoned, can resume to in_progress. abandoned = terminal, will not pursue.
	Status GoalStatus `json:"status"`
	// PARA Area of Responsibility this goal belongs to. FK to areas. SET NULL on area deletion — goal survives unclassified. NULL = no area assigned.
	AreaID *uuid.UUID `json:"area_id"`
	// Target quarter (e.g. "Q1 2026"). Free-form text. NULL = no quarter assigned.
	Quarter *string `json:"quarter"`
	// Hard deadline if any. NULL = no deadline.
	Deadline *time.Time `json:"deadline"`
	// Provenance. NULL = system/admin origin; an agent name marks a goal that agent proposed. NULLABLE with no default, mirroring areas.created_by.
	CreatedBy *string `json:"created_by"`
	// Agent's why-propose-this-now justification, captured on a proposed row and shown to the owner in admin triage to support activate/reject. NULL for admin/seeded rows and acceptable to keep or clear on activation.
	ProposalRationale *string   `json:"proposal_rationale"`
	CreatedAt         time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Goal progress checkpoints — binary completion markers within a goal. Milestones and projects are siblings under a goal: a project advances a goal through work, a milestone marks progress. Completion determined by completed_at IS NOT NULL — no separate status column. Goal progress = completed milestones / total milestones (advisory, not auto-derived). NOT OKR Key Results — milestones are binary (done/not-done), not quantitative metrics with target_value/current_value.
type Milestone struct {
	ID uuid.UUID `json:"id"`
	// Descriptive, measurable checkpoint name (e.g. "N3 合格", "API layer complete"). UNIQUE per goal — no duplicate milestone names within the same goal.
	Title string `json:"title"`
	// Detail on what this milestone means and how to measure achievement. Empty string = no detail provided.
	Description string `json:"description"`
	// Parent goal. NOT NULL — every milestone must belong to a goal. CASCADE on delete.
	GoalID uuid.UUID `json:"goal_id"`
	// Target completion date. NULL = no time target (pure checkpoint). Enables mid-goal on-track/at-risk analysis in weekly summary.
	TargetDeadline *time.Time `json:"target_deadline"`
	// When this milestone was achieved. NULL = not yet completed. This is the sole completion indicator — no status enum.
	CompletedAt *time.Time `json:"completed_at"`
	// Sequence position within a goal (0-based). Convention: position is the gap-free sequence index a row holds inside its parent; sort_order is the priority tier used for top-level UI ordering. See top-of-file ordering convention block.
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Run-history records for background processes. kind discriminates: crawl (internal crawl/fetch runs such as RSS feed collector), agent_schedule (external AI scheduler runs). Kind-specific fields live in metadata. subsystem carries the external-AI-scheduler identifier (only when kind=agent_schedule). RETENTION: 90 days for terminal runs; pending/running rows are operational state.
type ProcessRun struct {
	ID uuid.UUID `json:"id"`
	// Run category. Closed set: crawl (internal fetch/collector runs), agent_schedule (external AI scheduler runs). New kinds require CHECK update + Go writer. Use this column for dashboards, retention scoping, and metric labels.
	Kind string `json:"kind"`
	// External AI scheduler identifier. NOT NULL iff kind='agent_schedule' (chk_process_runs_subsystem_iff_agent_schedule). Values mirror agent.Platform in BuiltinAgents() for agents with non-empty Schedule. Today the only value in use is 'claude-cowork'. Values are validated at the Go write path, not by a hardcoded CHECK list — new AI schedulers (e.g. hermes-agent) land without a schema migration.
	Subsystem *string `json:"subsystem"`
	// Run identifier within its kind. crawl: collector name (e.g. "rss-feed-collector"). agent_schedule: "<agent_name>:<schedule_name>" composite from the Go dispatcher.
	Name string `json:"name"`
	// Lifecycle: pending → running → completed | failed | skipped. chk_process_runs_error_on_failure ties error to failed status. chk_process_runs_ended_at_consistency ties ended_at to terminal states.
	Status string `json:"status"`
	// For kind=crawl runs that process a content row. SET NULL on content deletion — diagnostics retained. NULL for runs that do not operate on a single content.
	ContentID *uuid.UUID `json:"content_id"`
	// Run input payload (JSONB). Structure varies by kind/name. NULL for kinds with no structured input.
	Input json.RawMessage `json:"input"`
	// Run output payload (JSONB). NULL until run completes. Structure varies by kind/name.
	Output json.RawMessage `json:"output"`
	// Error message on failure. NULL on non-failed status, enforced by chk_process_runs_error_on_failure.
	Error *string `json:"error"`
	// Current retry attempt (0-based). Incremented on each retry.
	Attempt int32 `json:"attempt"`
	// Maximum retry attempts allowed. Must be > 0.
	MaxAttempts int32 `json:"max_attempts"`
	// When execution began. NULL if still pending.
	StartedAt *time.Time `json:"started_at"`
	// When execution completed/failed/skipped. NULL while pending or running. NULL + old started_at = abandoned/crashed run.
	EndedAt *time.Time `json:"ended_at"`
	// Kind-specific fields not warranting promotion. crawl: { source_url, item_count, http_status }. agent_schedule: { produced_task_ids, missed_run_policy }. Promote to a column when a field needs WHERE/JOIN/GROUP BY ≥ 3 times in queries.
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

// PARA projects — planning aggregate, execution vehicles. Short-term efforts with clear outcomes. Projects and milestones are siblings under a goal: a project may advance a goal without mapping to a specific milestone. Public portfolio/case-study fields live in project_profiles (1:1).
type Project struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	// Lifecycle: proposed → planned | in_progress → on_hold → completed | maintained | archived. proposed = agent-proposed draft, inert — excluded from the admin project list, the public portfolio, and the goal project view; the owner activates it to in_progress in admin triage or rejects (hard DELETE). Slug/alias/title/id resolvers still match a proposed project so capture_inbox can link a todo to it before activation. archived = no longer active.
	Status ProjectStatus `json:"status"`
	// GitHub repository full name (e.g. Koopa0/koopa0.dev). Informational only — used by activity event resolution.
	Repo *string `json:"repo"`
	// PARA Area of Responsibility. FK to areas. SET NULL on area deletion. NULL = unclassified.
	AreaID *uuid.UUID `json:"area_id"`
	// Which goal this project serves. Nullable — a project can exist without a goal (PARA: some projects are pure Area maintenance, not goal-driven). SET NULL on goal deletion.
	GoalID   *uuid.UUID `json:"goal_id"`
	Deadline *time.Time `json:"deadline"`
	// Timestamp of most recent activity event for this project. Updated by cron.
	LastActivityAt *time.Time `json:"last_activity_at"`
	// Expected development activity frequency. NULL = not set.
	ExpectedCadence *string `json:"expected_cadence"`
	// Provenance. NULL = system/admin origin; an agent name marks a project that agent proposed. NULLABLE with no default, mirroring goals.created_by / areas.created_by.
	CreatedBy *string `json:"created_by"`
	// Agent's why-propose-this-now justification, captured on a proposed row and shown to the owner in admin triage to support activate/reject. NULL for admin/seeded rows and acceptable to keep or clear on activation.
	ProposalRationale *string   `json:"proposal_rationale"`
	CreatedAt         time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Maps variant project names to canonical project. Used by activity event and MCP search to resolve fuzzy project references.
type ProjectAlias struct {
	ID uuid.UUID `json:"id"`
	// Variant name (e.g. repo name, external title variant). Case-insensitive unique — "Koopa0.dev" and "koopa0.dev" are the same alias.
	Alias string `json:"alias"`
	// References canonical project. CASCADE — aliases meaningless without project.
	ProjectID uuid.UUID `json:"project_id"`
	// Where this alias was discovered (e.g. github, manual).
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

// Public portfolio / case-study facet of a project. 1:1 with projects (project_id PK). Lifecycle is independent: a profile can be edited long after its project completed. Existence of a row means the project has been curated for public display (even if is_public=false). CASCADE on project deletion — orphaned profiles make no sense. Invariant: is_public=true is only permitted when the owning projects.status != 'archived'. Enforced by trg_project_profile_not_public_if_archived (structural invariant trigger); archived→private demote on the project side runs in internal/project.Store.UpdateStatus.
type ProjectProfile struct {
	ProjectID uuid.UUID `json:"project_id"`
	// Extended description for project detail page. NULL = use projects.description.
	LongDescription *string `json:"long_description"`
	// User role in this project (e.g. Lead Engineer, Sole Developer). NULL = not specified.
	Role       *string  `json:"role"`
	TechStack  []string `json:"tech_stack"`
	Highlights []string `json:"highlights"`
	// Case study: what problem this project solves.
	Problem *string `json:"problem"`
	// Case study: how the problem was solved.
	Solution *string `json:"solution"`
	// Case study: system architecture description.
	Architecture *string `json:"architecture"`
	// Case study: measurable outcomes.
	Results *string `json:"results"`
	// Full GitHub repository URL. NULL = no public repo.
	GithubUrl *string `json:"github_url"`
	// Production deployment URL. NULL = not deployed.
	LiveUrl *string `json:"live_url"`
	// Cover image URL/path for portfolio cards. NULL = no cover.
	CoverImage *string `json:"cover_image"`
	// Whether to show on the public portfolio homepage. Requires is_public=true to take effect.
	Featured bool `json:"featured"`
	// Whether this profile is visible on the public website.
	IsPublic bool `json:"is_public"`
	// Display ordering in portfolio listings. Lower = higher priority.
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Literature reading shelf — one row per book, Koopa-private. Evaluation happens only through reading_reflections (dated diary entries); there is intentionally no rating column. Agent surface is read-only: list_readings and get_reading expose the shelf over MCP, and the shelf is part of the search_knowledge corpus (source_type=reading) via search_vector + embedding. No agent write path exists; mutations are admin HTTP only.
type Reading struct {
	ID uuid.UUID `json:"id"`
	// Book title as Koopa records it. Required, never blank (chk_reading_title_not_blank).
	Title string `json:"title"`
	// Author name(s), free text. Empty string when not recorded — "unknown author" carries no distinct meaning from "not entered", so NOT NULL DEFAULT '' instead of nullable.
	Author string `json:"author"`
	// Shelf state: want_to_read → reading → finished | abandoned. The CHECK closes the value set; transitions are NOT schema-enforced — any change is allowed (abandoned books get picked back up, finished books get re-read). Set by the admin HTTP handler, never by trigger.
	Status string `json:"status"`
	// Date Koopa started reading. NULL while the book sits on the want-to-read shelf or when the start date was never recorded.
	StartedOn *time.Time `json:"started_on"`
	// Date Koopa finished (or gave up on) the book. NULL until the reading concludes. The handler auto-stamps today on a transition to finished when no explicit date is supplied.
	FinishedOn *time.Time `json:"finished_on"`
	// Reserved for a future public shelf. Default false; nothing public-facing reads this yet — flipping it has no effect until a public surface exists.
	IsPublic bool `json:"is_public"`
	// Optional link to the goal this book serves (e.g. reading toward a learning objective). NULL when the book stands on its own — most books do, so nullable rather than required. ON DELETE SET NULL: deleting a goal unlinks the book, never deletes it. Inert until goals exist; set via admin.
	GoalID *uuid.UUID `json:"goal_id"`
	// Row creation time. Set by the database, never updated.
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
	// pgvector embedding (1536d) from gemini-embedding-2, derived from title + author. NULL until the background reconciler fills it; feeds the search_knowledge semantic branch (source_type=reading). See internal/embedder.Dimension — schema + Go must match exactly or pgvector rejects writes.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector for full-text search over the shelf row. 'simple' config (no stemming) for multilingual safety. Weight A = title, B = author. Backs the search_knowledge FTS branch (source_type=reading); a reflection-body hit comes from reading_reflections.search_vector instead.
	SearchVector interface{} `json:"search_vector"`
}

// Reading diary — dated entries under one book, shown as a time-ordered thread (entry_date, then created_at) on the book page. Many per book. Private like readings: no agent write path, admin HTTP only. A body hit is searchable via search_knowledge, folded under the parent book (source_type=reading).
type ReadingReflection struct {
	ID uuid.UUID `json:"id"`
	// The book this entry belongs to. ON DELETE CASCADE — deleting a book deletes its entire diary; the entries have no meaning without the book.
	ReadingID uuid.UUID `json:"reading_id"`
	// The diary date the entry belongs to — the day of reading, not necessarily the day it was typed in. Defaults to the current date; the handler applies the same default when the field is omitted.
	EntryDate time.Time `json:"entry_date"`
	// The diary entry text. Required, never blank (chk_reading_reflection_body_not_blank). Free-form prose; newlines allowed.
	Body string `json:"body"`
	// Row creation time. Tiebreak for thread ordering when two entries share an entry_date.
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
	// pgvector embedding (1536d) from gemini-embedding-2, derived from the diary body. NULL until the background reconciler fills it. A hit here surfaces in search_knowledge under source_type=reading, linked to the parent book.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector over the diary body (first 10K chars), 'simple' config for multilingual safety. Backs the search_knowledge FTS branch; a hit folds under the parent reading (source_type=reading), not a separate corpus.
	SearchVector interface{} `json:"search_vector"`
}

// JWT refresh token hashes. One user may have multiple active tokens (multi-device).
type RefreshToken struct {
	ID uuid.UUID `json:"id"`
	// Token owner. CASCADE — user deletion invalidates all tokens.
	UserID uuid.UUID `json:"user_id"`
	// Bcrypt or SHA256 hash of the actual token. Never store plaintext.
	TokenHash string `json:"token_hash"`
	// Absolute expiration. Tokens past this time are invalid and eligible for cleanup.
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// ヨルシカ song shelf — one row per song, Koopa-private. Reflections live in song_reflections (dated thread). No rating column; no agent write path, admin HTTP only. The shelf gained read-only search visibility: it is part of the search_knowledge corpus (source_type=song) via search_vector + embedding, but no MCP write tool touches it.
type Song struct {
	ID uuid.UUID `json:"id"`
	// Japanese song title (original). Required, never blank (chk_song_title_ja_not_blank).
	TitleJa string `json:"title_ja"`
	// Album name as a free-text grouping label. No album entity, no narrative relation (v1). Empty string when not recorded.
	Album string `json:"album"`
	// Japanese lyrics. Owner-filled for study; never generated. Empty until entered.
	LyricsJa string `json:"lyrics_ja"`
	// Owner translation of the lyrics. Owner-filled; never generated. Empty until entered.
	Translation string `json:"translation"`
	// Vocabulary notes for Japanese study (free-form). Owner-filled; never generated. Empty until entered.
	Vocabulary string `json:"vocabulary"`
	// Reserved for a future public surface. Default false; nothing public-facing reads this yet.
	IsPublic bool `json:"is_public"`
	// Row creation time. Set by the database, never updated.
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
	// pgvector embedding (1536d) from gemini-embedding-2, derived from title_ja + album + the study fields (lyrics/translation/vocabulary). NULL until the background reconciler fills it; feeds the search_knowledge semantic branch (source_type=song). See internal/embedder.Dimension — schema + Go must match exactly or pgvector rejects writes.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector for full-text search over the song row. 'simple' config for multilingual safety. Weight A = title_ja, B = album, C = owner translation (first 5K chars) — the translation gives the otherwise Japanese-only row lexical reach in the owner's working language. Backs the search_knowledge FTS branch (source_type=song).
	SearchVector interface{} `json:"search_vector"`
}

// Song reflection diary — dated entries under one song (理解/感受/意境), shown as a thread ordered by (entry_date, created_at). Many per song. Private like songs: no agent write path, admin HTTP only. A body hit is searchable via search_knowledge, folded under the parent song (source_type=song).
type SongReflection struct {
	ID uuid.UUID `json:"id"`
	// The song this entry belongs to. ON DELETE CASCADE — deleting a song deletes its entire reflection thread; the entries have no meaning without the song.
	SongID uuid.UUID `json:"song_id"`
	// The reflection date — the day of listening/understanding, not necessarily the typing date. Defaults to the current date; the handler applies the same default when omitted.
	EntryDate time.Time `json:"entry_date"`
	// The reflection text. Required, never blank (chk_song_reflection_body_not_blank). Free-form prose; newlines allowed.
	Body string `json:"body"`
	// Row creation time. Tiebreak for thread ordering when two entries share an entry_date.
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
	// pgvector embedding (1536d) from gemini-embedding-2, derived from the reflection body. NULL until the background reconciler fills it. A hit here surfaces in search_knowledge under source_type=song, linked to the parent song.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector over the reflection body (first 10K chars), 'simple' config for multilingual safety. Backs the search_knowledge FTS branch; a hit folds under the parent song (source_type=song), not a separate corpus.
	SearchVector interface{} `json:"search_vector"`
}

// Personal GTD work items. Distinct from the tasks coordination entity (inter-agent work units). Lifecycle: inbox (captured, not clarified) → todo (clarified, actionable) → in_progress → done. someday = interested but not now, reviewed in Weekly Review. inbox items lack project/due/priority — clarification promotes them to todo.
type Todo struct {
	ID uuid.UUID `json:"id"`
	// Short summary of the todo. Non-blank (chk_todo_title_not_blank).
	Title string `json:"title"`
	// GTD lifecycle: inbox → todo | someday. todo → in_progress → done. inbox = captured but not clarified (missing project/due/priority). someday = interested but not acting now — reviewed periodically. archived | dismissed = terminal self-close states set by an agent via the resolve_task MCP readback loop on a todo it created (archived = filed away, dismissed = won't do); like every non-done state they keep completed_at NULL, enforced by chk_todo_completed_at_consistency.
	State TodoState `json:"state"`
	// Due date. NULL = no deadline.
	Due *time.Time `json:"due"`
	// Optional parent project. SET NULL on project deletion — the todo survives unclassified.
	ProjectID *uuid.UUID `json:"project_id"`
	// When the todo was completed. NULL unless state=done, enforced by chk_todo_completed_at_consistency.
	CompletedAt *time.Time `json:"completed_at"`
	// Required energy level for GTD engage-by-energy. NULL = not set.
	Energy *string `json:"energy"`
	// Todo priority for GTD engage-by-priority. NULL = not set.
	Priority *string `json:"priority"`
	// Recurrence frequency count. NULL = non-recurring. Paired with recur_unit by chk_todo_recurrence_pair.
	RecurInterval *int32 `json:"recur_interval"`
	// Recurrence unit. NULL = non-recurring todo.
	RecurUnit *string `json:"recur_unit"`
	// Free-text detail. Empty string = no detail.
	Description string `json:"description"`
	// Which agent created or imported this todo into the system. FK to agents. Default human. Examples: human (manual or synced from external tool), planner (morning briefing).
	CreatedBy string `json:"created_by"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
	// Set explicitly by application in UPDATE queries. No trigger — application-managed.
	UpdatedAt time.Time `json:"updated_at"`
}

// Per-occurrence skip history for recurring todo items. RETENTION: 1 year. Scope discipline vs daily_plan_items.status='dropped': todo_skips records that a RECURRING todo's scheduled occurrence did not happen; daily_plan_items (status=dropped) records that a planner explicitly removed the todo from a specific day's plan. Both can apply to the same (todo_id, date) in theory — by convention, the cron-driven skip detection runs AFTER daily_plan reconciliation each night, so a todo the user dropped from today's plan does NOT also get a todo_skips row. Writers MUST preserve this order: daily_plan_items(dropped) first, todo_skips after. Analytics that count "missed occurrences" should SELECT only todo_skips; plan adherence metrics use daily_plan_items.
type TodoSkip struct {
	ID uuid.UUID `json:"id"`
	// Which recurring todo was skipped. CASCADE — skips die with their todo.
	TodoID uuid.UUID `json:"todo_id"`
	// Due date when skip was detected by cron.
	OriginalDue time.Time `json:"original_due"`
	// The occurrence date that was missed.
	SkippedDate time.Time `json:"skipped_date"`
	// auto-expired (cron detected overdue) or manual (user skipped).
	Reason string `json:"reason"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// High-level knowledge domains (Go, AI, System Design). 10-20, manually managed. Used for content categorization and feed association.
type Topic struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier (e.g. system-design, or 日本語). Used in feed_topics and content_topics junctions. Format (chk_topic_slug_format): hyphen-separated segments, no whitespace or slash, no leading/trailing/consecutive hyphens. Unicode letters/numbers (incl. CJK) allowed — slugs carry UTF-8 in URLs.
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// Optional emoji or icon identifier for UI display.
	Icon *string `json:"icon"`
	// Priority tier for display ordering (lower = higher priority). Convention: sort_order is for tier-based UI placement that may have gaps; position is for sequence-based 0-based indexing within a parent. See top-of-file ordering convention block.
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// System users. Single admin today; RBAC is a future concern with no current gate consumer.
type User struct {
	ID uuid.UUID `json:"id"`
	// Login identity. Unique. Basic structural validation via chk_users_email_format (full RFC 5322 compliance is enforced at the application layer).
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}
