// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type AgentNoteKind string

const (
	AgentNoteKindPlan       AgentNoteKind = "plan"
	AgentNoteKindContext    AgentNoteKind = "context"
	AgentNoteKindReflection AgentNoteKind = "reflection"
)

func (e *AgentNoteKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentNoteKind(s)
	case string:
		*e = AgentNoteKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentNoteKind: %T", src)
	}
	return nil
}

type NullAgentNoteKind struct {
	AgentNoteKind AgentNoteKind `json:"agent_note_kind"`
	Valid         bool          `json:"valid"` // Valid is true if AgentNoteKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentNoteKind) Scan(value interface{}) error {
	if value == nil {
		ns.AgentNoteKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentNoteKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentNoteKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentNoteKind), nil
}

type AgentStatus string

const (
	AgentStatusActive  AgentStatus = "active"
	AgentStatusRetired AgentStatus = "retired"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Valid       bool        `json:"valid"` // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type ContentStatus string

const (
	ContentStatusDraft     ContentStatus = "draft"
	ContentStatusReview    ContentStatus = "review"
	ContentStatusPublished ContentStatus = "published"
	ContentStatusArchived  ContentStatus = "archived"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus `json:"content_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

type ContentType string

const (
	ContentTypeArticle  ContentType = "article"
	ContentTypeEssay    ContentType = "essay"
	ContentTypeBuildLog ContentType = "build-log"
	ContentTypeTil      ContentType = "til"
	ContentTypeDigest   ContentType = "digest"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type EventType string

const (
	EventTypeNoteCreated      EventType = "note_created"
	EventTypeNoteUpdated      EventType = "note_updated"
	EventTypePush             EventType = "push"
	EventTypePullRequest      EventType = "pull_request"
	EventTypeProjectUpdate    EventType = "project_update"
	EventTypeTodoStateChange  EventType = "todo_state_change"
	EventTypeBookProgress     EventType = "book_progress"
	EventTypeGoalUpdate       EventType = "goal_update"
	EventTypeTodoCompleted    EventType = "todo_completed"
	EventTypeContentPublished EventType = "content_published"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type FeedEntryStatus string

const (
	FeedEntryStatusUnread  FeedEntryStatus = "unread"
	FeedEntryStatusRead    FeedEntryStatus = "read"
	FeedEntryStatusCurated FeedEntryStatus = "curated"
	FeedEntryStatusIgnored FeedEntryStatus = "ignored"
)

func (e *FeedEntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedEntryStatus(s)
	case string:
		*e = FeedEntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedEntryStatus: %T", src)
	}
	return nil
}

type NullFeedEntryStatus struct {
	FeedEntryStatus FeedEntryStatus `json:"feed_entry_status"`
	Valid           bool            `json:"valid"` // Valid is true if FeedEntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FeedEntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedEntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedEntryStatus), nil
}

type FlowStatus string

const (
	FlowStatusPending   FlowStatus = "pending"
	FlowStatusRunning   FlowStatus = "running"
	FlowStatusCompleted FlowStatus = "completed"
	FlowStatusFailed    FlowStatus = "failed"
)

func (e *FlowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlowStatus(s)
	case string:
		*e = FlowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlowStatus: %T", src)
	}
	return nil
}

type NullFlowStatus struct {
	FlowStatus FlowStatus `json:"flow_status"`
	Valid      bool       `json:"valid"` // Valid is true if FlowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlowStatus), nil
}

type GoalStatus string

const (
	GoalStatusNotStarted GoalStatus = "not-started"
	GoalStatusInProgress GoalStatus = "in-progress"
	GoalStatusDone       GoalStatus = "done"
	GoalStatusAbandoned  GoalStatus = "abandoned"
	GoalStatusOnHold     GoalStatus = "on-hold"
)

func (e *GoalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoalStatus(s)
	case string:
		*e = GoalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GoalStatus: %T", src)
	}
	return nil
}

type NullGoalStatus struct {
	GoalStatus GoalStatus `json:"goal_status"`
	Valid      bool       `json:"valid"` // Valid is true if GoalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GoalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoalStatus), nil
}

type HypothesisState string

const (
	HypothesisStateUnverified  HypothesisState = "unverified"
	HypothesisStateVerified    HypothesisState = "verified"
	HypothesisStateInvalidated HypothesisState = "invalidated"
	HypothesisStateArchived    HypothesisState = "archived"
)

func (e *HypothesisState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HypothesisState(s)
	case string:
		*e = HypothesisState(s)
	default:
		return fmt.Errorf("unsupported scan type for HypothesisState: %T", src)
	}
	return nil
}

type NullHypothesisState struct {
	HypothesisState HypothesisState `json:"hypothesis_state"`
	Valid           bool            `json:"valid"` // Valid is true if HypothesisState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHypothesisState) Scan(value interface{}) error {
	if value == nil {
		ns.HypothesisState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HypothesisState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHypothesisState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HypothesisState), nil
}

type MessageRole string

const (
	MessageRoleRequest  MessageRole = "request"
	MessageRoleResponse MessageRole = "response"
)

func (e *MessageRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageRole(s)
	case string:
		*e = MessageRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageRole: %T", src)
	}
	return nil
}

type NullMessageRole struct {
	MessageRole MessageRole `json:"message_role"`
	Valid       bool        `json:"valid"` // Valid is true if MessageRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageRole) Scan(value interface{}) error {
	if value == nil {
		ns.MessageRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageRole), nil
}

type ProjectStatus string

const (
	ProjectStatusPlanned    ProjectStatus = "planned"
	ProjectStatusInProgress ProjectStatus = "in-progress"
	ProjectStatusOnHold     ProjectStatus = "on-hold"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusMaintained ProjectStatus = "maintained"
	ProjectStatusArchived   ProjectStatus = "archived"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus `json:"project_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

type ReviewLevel string

const (
	ReviewLevelAuto     ReviewLevel = "auto"
	ReviewLevelLight    ReviewLevel = "light"
	ReviewLevelStandard ReviewLevel = "standard"
	ReviewLevelStrict   ReviewLevel = "strict"
)

func (e *ReviewLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewLevel(s)
	case string:
		*e = ReviewLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewLevel: %T", src)
	}
	return nil
}

type NullReviewLevel struct {
	ReviewLevel ReviewLevel `json:"review_level"`
	Valid       bool        `json:"valid"` // Valid is true if ReviewLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewLevel), nil
}

type ReviewStatus string

const (
	ReviewStatusPending  ReviewStatus = "pending"
	ReviewStatusApproved ReviewStatus = "approved"
	ReviewStatusRejected ReviewStatus = "rejected"
	ReviewStatusEdited   ReviewStatus = "edited"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type SourceType string

const (
	SourceTypeObsidian    SourceType = "obsidian"
	SourceTypeNotion      SourceType = "notion"
	SourceTypeAiGenerated SourceType = "ai-generated"
	SourceTypeExternal    SourceType = "external"
	SourceTypeManual      SourceType = "manual"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType `json:"source_type"`
	Valid      bool       `json:"valid"` // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type TaskState string

const (
	TaskStateSubmitted TaskState = "submitted"
	TaskStateWorking   TaskState = "working"
	TaskStateCompleted TaskState = "completed"
	TaskStateCanceled  TaskState = "canceled"
)

func (e *TaskState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskState(s)
	case string:
		*e = TaskState(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskState: %T", src)
	}
	return nil
}

type NullTaskState struct {
	TaskState TaskState `json:"task_state"`
	Valid     bool      `json:"valid"` // Valid is true if TaskState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskState) Scan(value interface{}) error {
	if value == nil {
		ns.TaskState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskState), nil
}

type TodoState string

const (
	TodoStateInbox      TodoState = "inbox"
	TodoStateTodo       TodoState = "todo"
	TodoStateInProgress TodoState = "in_progress"
	TodoStateDone       TodoState = "done"
	TodoStateSomeday    TodoState = "someday"
)

func (e *TodoState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoState(s)
	case string:
		*e = TodoState(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoState: %T", src)
	}
	return nil
}

type NullTodoState struct {
	TodoState TodoState `json:"todo_state"`
	Valid     bool      `json:"valid"` // Valid is true if TodoState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoState) Scan(value interface{}) error {
	if value == nil {
		ns.TodoState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoState), nil
}

// DB projection of the Go BuiltinAgents() registry. Rows are upserted at startup by agent.SyncToTable. Capability flags are NOT stored here — authorization is enforced in Go via the agent.Authorized compile-time wrapper. FK targets for tasks.requester / tasks.assignee use ON DELETE RESTRICT so historical coordination records cannot dangle. Removed registry entries transition to status=retired rather than being deleted.
type Agent struct {
	// Unique agent identifier. Used as requester/assignee in tasks and as the caller identity (as: field) in MCP tool calls. Matches the Go Agent.Name literal in BuiltinAgents(). Format: lowercase, must start with a letter, alphanumeric + hyphens (chk_agent_name_format).
	Name string `json:"name"`
	// Human-readable label for admin UI and logs. Non-blank (chk_agent_display_name_not_blank).
	DisplayName string `json:"display_name"`
	// Execution context. Closed set: claude-cowork, claude-code, claude-web, human (chk_agent_platform). Informational label — routing decisions are driven by agent registry lookups, not this column.
	Platform string `json:"platform"`
	// Short role description. Empty string = no description.
	Description string `json:"description"`
	// active = currently present in BuiltinAgents(). retired = previously registered but no longer in the Go literal. chk_agent_status_retired ties retired_at to status=retired.
	Status AgentStatus `json:"status"`
	// When this row was last reconciled with BuiltinAgents() by agent.SyncToTable. Updated on every startup sync.
	SyncedAt time.Time `json:"synced_at"`
	// When this agent was retired (removed from BuiltinAgents). NULL while status=active. Set by SyncToTable when the registry entry disappears.
	RetiredAt *time.Time `json:"retired_at"`
	// When the row was first upserted. Useful for onboarding audit.
	CreatedAt time.Time `json:"created_at"`
}

// Agent's internal narrative log — plans, context snapshots, reflections. Self-directed, not inter-agent coordination. Produced by a single agent across a session or day. metrics kind was removed in the coordination rebuild (no current writer).
type AgentNote struct {
	ID int64 `json:"id"`
	// plan = daily plan. context = end-of-session state. reflection = retrospective review.
	Kind AgentNoteKind `json:"kind"`
	// Which agent wrote this note. FK to agents. Renamed from "source" to disambiguate agent identity from system origin (events.source) and origin reference (contents.origin_ref).
	Author string `json:"author"`
	// Free-text body of the note. Markdown allowed.
	Content string `json:"content"`
	// Structured metadata per kind. plan: {reasoning}. Daily todo selection is tracked in daily_plan_items, not here. context, reflection: no required metadata schema.
	Metadata json.RawMessage `json:"metadata"`
	// The logical date this note belongs to. May differ from created_at for backfilled notes.
	EntryDate time.Time `json:"entry_date"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// Append-only execution history for agent-owned schedules. Schedule definitions live in the Go registry (BuiltinAgents), not in a DB table — schedule_name here is the "<agent>:<schedule>" composite key produced by the dispatcher. No FK: Go validates the name against the registry before insert.
type AgentScheduleRun struct {
	ID int64 `json:"id"`
	// Composite key "<agent_name>:<schedule_name>" from the Go registry. Free text at the DB layer — historical rows survive registry edits without dangling.
	ScheduleName string `json:"schedule_name"`
	// success = run completed without execution error. failure = errored. skipped = missed-run policy decided to skip. Note: success does not guarantee expected outputs were produced — output completeness is a separate monitoring concern.
	Status string `json:"status"`
	// When the scheduled run began.
	StartedAt time.Time `json:"started_at"`
	// When the run finished. NULL = still running or crashed. NULL + old started_at = abandoned/crashed run (same pattern as sessions.ended_at).
	EndedAt *time.Time `json:"ended_at"`
	// Error details on failure. NULL on success/skip, enforced by chk_agent_schedule_run_error_on_failure.
	Error *string `json:"error"`
	// Run-specific data: produced task IDs, execution duration, backend-specific info.
	Metadata json.RawMessage `json:"metadata"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// PARA Areas of Responsibility — ongoing domains requiring sustained attention. Unlike projects (which complete), areas persist indefinitely. Each area has a standard to maintain, not a goal to achieve. Goals and projects reference areas via FK.
type Area struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier (e.g. backend, learning, studio). Used in filters and API.
	Slug string `json:"slug"`
	// Display name (e.g. Backend, Learning, Studio).
	Name string `json:"name"`
	// What this area of responsibility covers and what "maintaining the standard" means.
	Description string `json:"description"`
	// Optional emoji or icon identifier for UI display.
	Icon *string `json:"icon"`
	// Display ordering. Lower = higher priority.
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Structured deliverables produced by the target agent during or after task work. Separate from conversation messages because deliverables (research reports, document outputs) have an independent lifetime. Size bounds (32 parts, 256 KB) are looser than task_messages bounds.
type Artifact struct {
	ID uuid.UUID `json:"id"`
	// Parent task. CASCADE — artifacts die with their task.
	TaskID uuid.UUID `json:"task_id"`
	// Short label identifying this artifact (e.g. "weekly-report", "architecture-diagram").
	Name string `json:"name"`
	// Optional longer description. Empty string = no description.
	Description string `json:"description"`
	// JSONB array of a2a.Part values (same format as task_messages.parts). Stores the actual deliverable content.
	Parts []byte `json:"parts"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// External resources curated with personal commentary. Separate from contents because bookmarks skip editorial review (curate = publish), have an external canonical URL, and do not share the first-party publish workflow.
type Bookmark struct {
	ID uuid.UUID `json:"id"`
	// Canonical external URL of the bookmarked resource. Must use http(s) scheme (chk_bookmark_url_scheme). SEO canonical tag points to this value.
	Url string `json:"url"`
	// SHA-256 hex digest of the canonical URL (chk_bookmark_url_hash_format — exactly 64 hex chars). Dedup identity. Computed in application code before INSERT — matches feed_entries.url_hash semantics.
	UrlHash string `json:"url_hash"`
	// URL-safe internal identifier for bookmark permalinks on the koopa0.dev site (chk_bookmark_slug_format). Distinct from the external URL.
	Slug string `json:"slug"`
	// Display title. May override the source title if the curator edited it at capture time. Non-blank (chk_bookmark_title_not_blank).
	Title string `json:"title"`
	// Short excerpt from the source, typically truncated to a few sentences. Empty string when the source provided none.
	Excerpt string `json:"excerpt"`
	// Curator's personal commentary. The reason this bookmark is worth remembering. Empty string when no note.
	Note string `json:"note"`
	// How the bookmark entered the system: rss (curated from feed_entries), manual (pasted by curator), shared (received via external channel).
	SourceType string `json:"source_type"`
	// If source_type=rss, references the originating feed_entries row. NULL for manual/shared bookmarks. SET NULL on feed_entry deletion — bookmark survives independently.
	SourceFeedEntryID *uuid.UUID `json:"source_feed_entry_id"`
	// Agent that curated the bookmark. FK to agents with ON DELETE RESTRICT — historical curation references never dangle, matching the same FK strategy as todos.assignee, agent_notes.author, hypotheses.author, etc.
	CuratedBy string `json:"curated_by"`
	// When the bookmark was curated into koopa0.dev. Distinct from source publication date.
	CuratedAt time.Time `json:"curated_at"`
	// Whether this bookmark is visible on the public website. Private bookmarks are admin/MCP only.
	IsPublic bool `json:"is_public"`
	// When the bookmark became publicly visible. NULL = private or not yet published. Unlike contents, bookmarks typically have published_at = curated_at.
	PublishedAt *time.Time `json:"published_at"`
	// pgvector embedding (768d) for semantic search inclusion. Optional — backfill may leave NULL for rows whose source content was never embedded.
	Embedding *pgvector_go.Vector `json:"embedding"`
	CreatedAt time.Time           `json:"created_at"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// Junction: bookmark ↔ tag. References canonical tags resolved through the tag_aliases pipeline.
type BookmarkTag struct {
	BookmarkID uuid.UUID `json:"bookmark_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

// Junction: bookmark ↔ topic. Many-to-many. Topics are curated knowledge domain categories (same taxonomy as content_topics).
type BookmarkTopic struct {
	BookmarkID uuid.UUID `json:"bookmark_id"`
	TopicID    uuid.UUID `json:"topic_id"`
}

// Learning ontology — concepts, patterns, skills, and principles that can be learned, practiced, and diagnosed. Independent from tags (which handle content classification). Hierarchy via parent_id (typical: pattern contains skill, skill refines principle — but kind ordering is convention, not DDL-enforced). Mastery is a derived state computed from attempt_observations aggregation, not stored on this table.
type Concept struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier. Case-insensitive uniqueness per domain enforced by idx_concepts_domain_slug. Convention: lowercase-kebab (e.g. binary-search, two-pointers, te-form).
	Slug string `json:"slug"`
	// Human-readable display name (e.g. "Binary Search", "Te-form Conjugation").
	Name string `json:"name"`
	// Learning domain: leetcode, japanese, system-design, go, english, reading, etc. Go-validated convention, not DB-enforced — domains expand as new learning areas are added. Deviation from schema-design.md CHECK rule is deliberate: domain set is open-ended and cross-cutting.
	Domain string `json:"domain"`
	// Concept classification. pattern: strategic framework (two-pointers, binary-search, sliding-window). skill: practicable ability (constraint-analysis, edge-case-handling). principle: theoretical foundation (amortized analysis, CAP theorem, N3 grammar). "knowledge" was rejected to avoid semantic overlap with notes.
	Kind string `json:"kind"`
	// Self-referencing hierarchy. Pattern "binary-search" → skill "recognize binary search on rotated array". SET NULL on parent deletion — children become roots. Acyclicity enforced by application, not database. Same-domain invariant: parent and child must share the same domain — cross-domain parenting is a data quality error, enforced by Go validation.
	ParentID *uuid.UUID `json:"parent_id"`
	// Optional cross-reference to the canonical tag system. When both a concept and a tag exist for the same thing, this FK bridges content classification (tag-based) and learning analytics (concept-based). SET NULL on tag deletion. Cardinality: many-to-one is intentional — multiple concepts across different domains may bridge to the same canonical tag (e.g. leetcode/binary-search and system-design/binary-search both link to tag binary-search).
	TagID *uuid.UUID `json:"tag_id"`
	// Optional elaboration. Empty string default — not nullable.
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Published content — the finished product. Five types share one table and one lifecycle: draft → review → published → archived.
type Content struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier. Globally unique. Used in public URLs. Format: lowercase alphanumeric segments separated by single hyphens (chk_content_slug_format).
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Body    string `json:"body"`
	Excerpt string `json:"excerpt"`
	// Content format: article, essay, build-log, til, digest. (note and bookmark removed in the coordination rebuild — they have their own dedicated tables.)
	Type ContentType `json:"type"`
	// Lifecycle: draft → review → published. archived = soft delete.
	Status ContentStatus `json:"status"`
	// Reference to the origin artifact — an Obsidian file path, an external URL, or NULL for manually created content. Renamed from contents.source to disambiguate from events.source (origin system) and tasks.requester (origin agent).
	OriginRef *string `json:"origin_ref"`
	// Origin system classification (obsidian, notion, ai-generated, external, manual). Distinct from origin_ref which carries the actual identifier.
	SourceType NullSourceType `json:"source_type"`
	// Groups content into a series. Paired with series_order (chk_contents_series).
	SeriesID *string `json:"series_id"`
	// Position within the series. Paired with series_id (chk_contents_series).
	SeriesOrder *int32 `json:"series_order"`
	// AI review strictness: auto (publish immediately), light, standard, strict (human approval required).
	ReviewLevel ReviewLevel `json:"review_level"`
	// AI pipeline metadata (JSONB). Structure: {summary, keywords, quality_score, review_notes}. Set by Genkit flows.
	AiMetadata json.RawMessage `json:"ai_metadata"`
	// Estimated reading time in minutes. Computed from body word count. Always >= 0.
	ReadingTimeMin int32 `json:"reading_time_min"`
	// Cover image URL or path for content cards and social sharing. NULL = no cover image.
	CoverImage *string `json:"cover_image"`
	// Whether this content is visible on the public website. Private content is admin/MCP only.
	IsPublic bool `json:"is_public"`
	// Associated project. SET NULL on project deletion — content survives independently.
	ProjectID *uuid.UUID `json:"project_id"`
	// When content was published. NULL = not yet published.
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   time.Time  `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
	// pgvector embedding (768d) for semantic search via HNSW index.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector for full-text search. Uses 'simple' config (no stemming/language-specific tokenization) for multilingual safety. Weight A = title, C = body (first 10K chars). Semantic search via embedding compensates for tsvector recall limitations.
	SearchVector string `json:"search_vector"`
}

type ContentTag struct {
	ContentID uuid.UUID `json:"content_id"`
	// References canonical tag. Distinct from content_topics: topics are curated categories, tags are raw labels resolved through the alias pipeline.
	TagID uuid.UUID `json:"tag_id"`
}

// Junction: content ↔ topic. Many-to-many. Curated knowledge domain categories.
type ContentTopic struct {
	ContentID uuid.UUID `json:"content_id"`
	TopicID   uuid.UUID `json:"topic_id"`
}

// Daily commitment records. Each row represents a todo item selected for a specific day's plan. Lifecycle: planned → done | deferred | dropped. Re-plan uses INSERT ... ON CONFLICT (plan_date, todo_id) DO UPDATE SET status = 'planned'.
type DailyPlanItem struct {
	ID uuid.UUID `json:"id"`
	// The date this todo was planned for. Combined with todo_id forms a unique constraint — one todo can appear at most once per day.
	PlanDate time.Time `json:"plan_date"`
	// The todo committed to. CASCADE on delete — if the todo is removed, the plan item goes too.
	TodoID uuid.UUID `json:"todo_id"`
	// Which agent added this item to the plan. Typically hq (morning briefing, cron auto-populate) or human (manual selection via MCP tool).
	SelectedBy string `json:"selected_by"`
	// Ordering within a day's plan. 0-based. Semantic: first item = highest priority for today.
	Position int32 `json:"position"`
	// Optional rationale for selecting this todo today. NULL = no specific reason recorded.
	Reason *string `json:"reason"`
	// Optional link to the agent_notes(kind=plan) entry that drove this planning session. All items from the same planning session share the same agent_note_id. Enables "which reasoning led to these todo selections" queries. Symmetric with sessions.agent_note_id — session produces the note, agent_note_id links back. SET NULL on note deletion.
	AgentNoteID *int64 `json:"agent_note_id"`
	// Lifecycle state. planned = committed for today. done = completed within this day (independent of todos.state for recurring todos). deferred = not done today, carry-over candidate for future planning. dropped = explicitly removed from plan, no intent to carry over.
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Tracks when status last changed. Critical for Weekly Review analysis and cron debug.
	UpdatedAt time.Time `json:"updated_at"`
}

// Weekly reconciliation run history for system health and drift trend analysis.
type DriftCheckRun struct {
	ID int64 `json:"id"`
	// When the reconciliation run began.
	StartedAt time.Time `json:"started_at"`
	// NULL until run finishes. NULL + old started_at = crashed run.
	CompletedAt *time.Time `json:"completed_at"`
	// Notes in Obsidian vault but not yet synced to DB.
	ObsidianMissing int32 `json:"obsidian_missing"`
	// Notes in DB but file no longer exists in Obsidian vault.
	ObsidianOrphaned int32 `json:"obsidian_orphaned"`
	// Projects in Notion but not yet synced to DB.
	NotionProjMissing int32 `json:"notion_proj_missing"`
	// Projects in DB but no longer in Notion source.
	NotionProjOrphan int32 `json:"notion_proj_orphan"`
	// Goals in Notion but not yet synced to DB.
	NotionGoalMissing int32 `json:"notion_goal_missing"`
	// Goals in DB but no longer in Notion source.
	NotionGoalOrphan int32 `json:"notion_goal_orphan"`
	// Sum of all missing+orphaned counts. Zero = fully consistent.
	TotalDrift int32 `json:"total_drift"`
	// Number of errors encountered during the run. 0 = clean run.
	ErrorCount int32 `json:"error_count"`
	// JSON array of error strings from the run. NULL when error_count=0.
	Errors    json.RawMessage `json:"errors"`
	CreatedAt time.Time       `json:"created_at"`
}

// Content review workflow. One pending review per content (idx_editorial_queue_pending_content).
type EditorialQueue struct {
	ID uuid.UUID `json:"id"`
	// References content under review. ON DELETE CASCADE — content deletion removes review record.
	ContentID uuid.UUID `json:"content_id"`
	// Snapshot of content.review_level at submission time. Does not live-update if content review_level changes.
	ReviewLevel ReviewLevel `json:"review_level"`
	// Lifecycle: pending → approved | rejected | edited. chk_reviewed_at_consistency ties reviewed_at to non-pending status.
	Status ReviewStatus `json:"status"`
	// Admin notes from the review. NULL = no notes.
	ReviewerNotes *string `json:"reviewer_notes"`
	// When this content was submitted for review.
	SubmittedAt time.Time `json:"submitted_at"`
	// When review was completed. NULL while status = pending, NOT NULL otherwise (enforced by chk_reviewed_at_consistency).
	ReviewedAt *time.Time `json:"reviewed_at"`
}

// Unified event log from all sources (GitHub, Notion, Obsidian sync, MCP, cron).
type Event struct {
	ID int64 `json:"id"`
	// Event ID in the origin system (e.g. GitHub delivery ID). Used for dedup.
	SourceID *string `json:"source_id"`
	// When the event occurred in the source system. Distinct from created_at (when the row was inserted into this DB). For webhook events, timestamp may predate created_at due to delivery delay.
	Timestamp time.Time `json:"timestamp"`
	// Event classification. PostgreSQL ENUM — closed contract, all values defined in Go code. Adding a new event type requires ALTER TYPE ADD VALUE + Go code change. UPGRADE PATH: if event types grow significantly after Gmail/Calendar integration, consider migrating from ENUM to TEXT + CHECK for easier extensibility.
	EventType EventType `json:"event_type"`
	// Origin system name (github, notion, obsidian, mcp, cron). NOT a participant — this is system-level.
	Source string `json:"source"`
	// Related project slug. Not FK — may reference projects not yet created or since renamed.
	Project *string `json:"project"`
	// GitHub repository full name (e.g. Koopa0/koopa0.dev).
	Repo *string `json:"repo"`
	// Git ref (branch name or tag).
	Ref *string `json:"ref"`
	// Event summary (e.g. commit message, PR title, task name).
	Title *string `json:"title"`
	// Event detail body. May contain markdown.
	Body *string `json:"body"`
	// Event-specific structured data (JSONB). GitHub: diff stats. Notion: changed fields.
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

// Junction: event ↔ tag. Many-to-many. Tags extracted from event metadata during ingestion.
type EventTag struct {
	EventID int64     `json:"event_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

// RSS/Atom feed subscriptions. Fetch pipeline pulls entries on schedule, scores relevance, and surfaces for curation.
type Feed struct {
	ID uuid.UUID `json:"id"`
	// Feed URL (RSS/Atom). Unique — one subscription per URL. Must use http(s) scheme (chk_feed_url_scheme).
	Url  string `json:"url"`
	Name string `json:"name"`
	// Fetch cadence label (hourly | daily | weekly | biweekly | monthly), enforced by chk_feed_schedule. The Go scheduler maps each label to a concrete time interval. NOT a cron expression — for cron-format schedules see topic_monitors.schedule.
	Schedule string `json:"schedule"`
	Enabled  bool   `json:"enabled"`
	// Feed importance for relevance scoring: high feeds get boosted scores.
	Priority string `json:"priority"`
	// HTTP ETag header from last fetch. NULL = never fetched or server did not return ETag.
	Etag *string `json:"etag"`
	// HTTP Last-Modified header from last fetch. NULL = never fetched or server did not return it.
	LastModified *string `json:"last_modified"`
	// When the feed was last successfully fetched. NULL = never fetched.
	LastFetchedAt *time.Time `json:"last_fetched_at"`
	// Number of consecutive fetch failures. Reset to 0 on success. Auto-disable threshold in Go.
	ConsecutiveFailures int32 `json:"consecutive_failures"`
	// Error message from last failed fetch. NULL = no error (last fetch succeeded or never fetched).
	LastError *string `json:"last_error"`
	// Why this feed was disabled. NULL = not disabled or no reason recorded.
	DisabledReason *string `json:"disabled_reason"`
	// Feed-specific filter rules (JSONB). Structure: {deny_paths, deny_title_patterns, deny_tags}. Empty {} = no filtering.
	FilterConfig json.RawMessage `json:"filter_config"`
	CreatedAt    time.Time       `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// RSS feed items collected by the fetch pipeline. IMPORTANT SEMANTICS: topics are inherited from feed via feed_topics junction at QUERY TIME, not snapshot at ingestion. This means changing a feed's topics retroactively changes all its entries' topic associations. This is a deliberate product choice — topics represent current feed configuration, not historical classification. If historical topic tracking is needed, add feed_entry_topics snapshot table.
type FeedEntry struct {
	ID uuid.UUID `json:"id"`
	// Original article URL.
	SourceUrl string `json:"source_url"`
	// Article title from the RSS feed. Raw — not cleaned or truncated.
	Title string `json:"title"`
	// RSS entry content/summary. Stores the raw feed content (HTML or text). DEFAULT '' — empty when feed provides no content element.
	OriginalContent string `json:"original_content"`
	// Keyword-weighted relevance score computed by fetch pipeline. Higher = more relevant to tracked topics.
	RelevanceScore float64 `json:"relevance_score"`
	// Curation lifecycle: unread → read → curated/ignored.
	Status FeedEntryStatus `json:"status"`
	// If curated into a bookmark/article, references the content record. SET NULL on content deletion.
	CuratedContentID *uuid.UUID `json:"curated_content_id"`
	// When the pipeline first fetched this entry.
	CollectedAt time.Time `json:"collected_at"`
	// Dedup identity — SHA256 of canonical source_url. NOT NULL — every entry must have dedup identity. Pipeline computes before INSERT.
	UrlHash string `json:"url_hash"`
	// Admin feedback on relevance scoring quality. Used to tune scoring parameters.
	UserFeedback *string `json:"user_feedback"`
	// When feedback was given. NULL = no feedback.
	FeedbackAt *time.Time `json:"feedback_at"`
	// Source feed. NULL after feed deletion (SET NULL) — entries retained for curation.
	FeedID *uuid.UUID `json:"feed_id"`
	// Original publication date from the feed. NULL if feed did not provide it.
	PublishedAt *time.Time `json:"published_at"`
}

// Which topics a feed covers. Replaces the old feeds.topics TEXT[] — proper FK instead of stringly-typed array.
type FeedTopic struct {
	FeedID  uuid.UUID `json:"feed_id"`
	TopicID uuid.UUID `json:"topic_id"`
}

// Genkit AI flow execution records. Each row = one run of a flow. Retryable via attempt/max_attempts. RETENTION: completed/failed runs older than 90 days should be archived or deleted by retention cron.
type FlowRun struct {
	ID uuid.UUID `json:"id"`
	// Genkit flow identifier (e.g. classify, summarize, review). Matches Go flow registration name.
	FlowName string `json:"flow_name"`
	// Content being processed. SET NULL on content deletion — run history retained for diagnostics.
	ContentID *uuid.UUID `json:"content_id"`
	// Flow input payload (JSONB). Structure varies by flow_name.
	Input []byte `json:"input"`
	// Flow output payload (JSONB). NULL until flow completes. Structure varies by flow_name.
	Output json.RawMessage `json:"output"`
	// Lifecycle: pending → running → completed | failed. chk_error_on_failure ties error to failed status.
	Status FlowStatus `json:"status"`
	// Error message on failure. NULL on non-failed status, enforced by chk_error_on_failure.
	Error *string `json:"error"`
	// Current retry attempt (0-based). Incremented on each retry.
	Attempt int32 `json:"attempt"`
	// Maximum retry attempts allowed. Must be > 0 (chk_max_attempts_positive).
	MaxAttempts int32 `json:"max_attempts"`
	// When the flow execution began. NULL if still pending.
	StartedAt *time.Time `json:"started_at"`
	// When the flow execution completed or failed. NULL if still running or pending.
	EndedAt   *time.Time `json:"ended_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// Planning objectives — aspirational outcomes with optional deadlines. Each goal may have milestones (progress checkpoints) and projects (execution vehicles). Milestone progress is advisory — goal status is managed manually, not auto-derived.
type Goal struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	// Lifecycle: not-started → in-progress → done | abandoned | on-hold. on-hold = paused but not abandoned, can resume to in-progress. abandoned = terminal, will not pursue.
	Status GoalStatus `json:"status"`
	// PARA Area of Responsibility this goal belongs to. FK to areas. SET NULL on area deletion — goal survives unclassified. NULL = no area assigned.
	AreaID *uuid.UUID `json:"area_id"`
	// Target quarter (e.g. "Q1 2026"). Free-form text. NULL = no quarter assigned.
	Quarter *string `json:"quarter"`
	// Hard deadline if any. NULL = no deadline.
	Deadline *time.Time `json:"deadline"`
	// External system this goal is synced from (e.g. "notion", "linear"). NULL = local-only. Replaces the previous notion_page_id field — generalised because koopa0.dev is moving away from Notion. Paired with external_ref via chk_goal_external_pair.
	ExternalProvider *string `json:"external_provider"`
	// Provider-specific identifier within external_provider (e.g. Notion page ID). NULL = not synced. UNIQUE per provider via uniq_goal_external.
	ExternalRef *string   `json:"external_ref"`
	CreatedAt   time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Falsifiable hypothesis tracker (was: insights). Each row carries a one-line falsifiable claim plus the invalidation condition that would disprove it. Evidence accumulates in metadata over time until the state transitions to verified or invalidated.
type Hypothesis struct {
	ID int64 `json:"id"`
	// Which agent recorded the hypothesis. FK to agents. Renamed from "source" to align with agent_notes.author and disambiguate agent identity from system origin.
	Author string `json:"author"`
	// Full narrative context. The claim column is the one-line prediction; content is the supporting analysis and evidence.
	Content string `json:"content"`
	// Lifecycle: unverified → verified | invalidated → archived.
	State HypothesisState `json:"state"`
	// One-line falsifiable prediction. Renamed from "hypothesis" to avoid the hypotheses.hypothesis stutter.
	Claim string `json:"claim"`
	// What would disprove the claim. Required — a hypothesis without an invalidation condition is not falsifiable and should not be recorded.
	InvalidationCondition string `json:"invalidation_condition"`
	// supporting_evidence, counter_evidence, conclusion, category, project, tags. Promote fields to columns when query patterns demand it.
	Metadata json.RawMessage `json:"metadata"`
	// Date the hypothesis was first observed or recorded.
	ObservedDate time.Time `json:"observed_date"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// Individual learning attempt records. One learning item can have multiple attempts (first try, revisit, re-practice). CASCADE from items — deleting an item deletes its attempt history. No is_revisit column — derivable as attempt_number > 1. Append-only — no updated_at.
type LearningAttempt struct {
	ID uuid.UUID `json:"id"`
	// The learning target attempted. CASCADE — attempts are meaningless without their item.
	LearningTargetID uuid.UUID `json:"learning_target_id"`
	// Optional link to the session this attempt occurred in. NULL for ad-hoc attempts outside a formal session. SET NULL on session deletion.
	SessionID *uuid.UUID `json:"session_id"`
	// Nth attempt at this item. 1 = first try, 2+ = revisit. Application must compute MAX(attempt_number) + 1 before inserting — DEFAULT 1 only applies to first attempts. UNIQUE with learning_target_id enforces no duplicate numbering.
	AttemptNumber int32 `json:"attempt_number"`
	// Two outcome paradigms coexist in this column. Problem-solving (LeetCode, drills): solved_independent (no help), solved_with_hint (nudge needed), solved_after_solution (saw answer first). Immersive (reading, listening, literary analysis): completed (finished independently), completed_with_support (needed dictionary, subtitles, translation, Claude annotation). Shared across both: incomplete (partially done), gave_up (could not proceed). MCP tool layer maps domain context to the appropriate paradigm.
	Outcome string `json:"outcome"`
	// Time spent on this attempt in minutes. NULL = not tracked. Must be positive.
	DurationMinutes *int32 `json:"duration_minutes"`
	// Free-text: where you got stuck. High cardinality, not a queryable category.
	StuckAt *string `json:"stuck_at"`
	// Free-text: what method you used. Coaching context, not a queryable enum.
	ApproachUsed *string `json:"approach_used"`
	// Optional link to an attempt-level working note. Distinct from learning_targets.obsidian_note_id (item-level summary). SET NULL on note deletion.
	ObsidianNoteID *int64 `json:"obsidian_note_id"`
	// Narrative data: coaching hints given, alternative approaches considered, code quality observations, LLM transcript excerpts. Not queryable — stays in JSONB. If a field needs WHERE/JOIN/GROUP BY, promote to a column.
	Metadata []byte `json:"metadata"`
	// When this attempt occurred. May differ from created_at if backfilled.
	AttemptedAt time.Time `json:"attempted_at"`
	CreatedAt   time.Time `json:"created_at"`
}

// Micro-cognitive signals observed during a specific attempt on a specific concept. Powers weakness overview, progression tracking, and drill-down UI. Append-only — no updated_at. CASCADE from attempts, RESTRICT from concepts.
type LearningAttemptObservation struct {
	ID uuid.UUID `json:"id"`
	// The attempt during which this signal was observed. CASCADE — observations die with their attempt.
	AttemptID uuid.UUID `json:"attempt_id"`
	// The concept this signal pertains to. RESTRICT — cannot delete a concept that has observations. To merge concepts: UPDATE observations to surviving concept_id first, then DELETE the old concept. Observations are irreplaceable historical analytics.
	ConceptID uuid.UUID `json:"concept_id"`
	// weakness: something went wrong with this concept during this attempt. improvement: noticeable progress compared to previous attempts. mastery: demonstrated independent, fluent application.
	SignalType string `json:"signal_type"`
	// Observation dimension. Go-validated convention, not DB ENUM — categories expand across domains. LeetCode: pattern-recognition, constraint-analysis, edge-cases, implementation, complexity-analysis, approach-selection. Japanese: conjugation-accuracy, particle-selection, listening-comprehension, vocabulary-recall. System Design: tradeoff-analysis, bottleneck-diagnosis, capacity-estimation.
	Category string `json:"category"`
	// Granularity within a signal. minor: forgot one edge case. moderate: correct approach, failed execution. critical: did not recognize the pattern at all. NULL for improvement/mastery signals where severity does not apply.
	Severity *string `json:"severity"`
	// Free-text evidence or explanation. NULL when the signal is self-explanatory from category alone.
	Detail *string `json:"detail"`
	// high (default): signal directly evidenced by the attempt outcome — user said "I forgot how X works" or repeatedly failed at X. low: coach inferred the signal from indirect evidence — user struggled with the problem and coach suspects X is the missing skill. Both persist. Dashboard mastery and weakness views default to high only; pass confidence_filter=all to include low-confidence observations.
	Confidence string    `json:"confidence"`
	CreatedAt  time.Time `json:"created_at"`
}

// Ordered, mutable learning curricula — a named commitment to practice a specific set of learning items. Plans serve aspirations (goals), not execution vehicles (projects). Status lifecycle: draft → active → completed/paused/abandoned. Draft = workspace/uncommitted. Active = committed curriculum being tracked against execution.
type LearningPlan struct {
	// Primary key. Auto-generated UUID.
	ID uuid.UUID `json:"id"`
	// Display title (e.g., "LeetCode 200 題計畫"). Not unique — allows v1/v2 scenarios.
	Title string `json:"title"`
	// Plan description, strategy notes. Empty string = no description.
	Description string `json:"description"`
	// Learning domain (same convention as concepts.domain). Go-validated, not DB-enforced.
	Domain string `json:"domain"`
	// Optional aspirational target. NULL = area-level maintenance plan (no specific goal). SET NULL on goal deletion.
	GoalID *uuid.UUID `json:"goal_id"`
	// Lifecycle state. draft → active → completed. Can pause from active, abandon from draft/active/paused. Draft plans are not tracked in execution. See mcp-decision-policy.md for mutation rules per status.
	Status string `json:"status"`
	// Advisory target item count (e.g., 200). NULL = open-ended plan. Not enforced by DB.
	TargetCount *int32 `json:"target_count"`
	// Plan-creation parameters that do NOT need WHERE/JOIN/GROUP BY. If any field needs filtering, promote to a column. Examples: difficulty_distribution, focus_areas, pacing_notes.
	PlanConfig []byte `json:"plan_config"`
	// Which agent created this plan. FK to agents. RESTRICT on delete — cannot remove an agent who owns plans.
	CreatedBy string `json:"created_by"`
	// Row creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Junction between plans and items — plan membership with ordering and per-item lifecycle. Same item can appear in multiple plans (cross-plan reuse). CASCADE from plan deletion. RESTRICT from item deletion — cannot silently remove items from a plan. Append-style with status tracking — no updated_at (status transitions are the audit trail).
type LearningPlanEntry struct {
	// Primary key. Auto-generated UUID.
	ID uuid.UUID `json:"id"`
	// Parent learning plan. CASCADE — deleting a plan removes all its items.
	PlanID uuid.UUID `json:"plan_id"`
	// The learning target included in this plan. RESTRICT on delete — cannot silently remove a plan item by deleting its catalog entry. Resolve plan references first.
	LearningTargetID uuid.UUID `json:"learning_target_id"`
	// Ordering within the plan (0-based). NOT unique in DB — application invariant maintains uniqueness. Follows milestones and daily_plan_items pattern.
	Position int32 `json:"position"`
	// Plan-item lifecycle: planned → completed (via explicit tool call after successful attempt) | skipped (plan decision to not do it) | substituted (replaced by another item). Distinct from attempt.outcome — plan_status is a plan-domain decision, not an execution result.
	Status string `json:"status"`
	// Optional grouping label within the plan (e.g., "1-arrays", "phase-2-trees"). Free-text with kebab-case validation enforced in Go, not DB. NULL = no phase grouping.
	Phase *string `json:"phase"`
	// If status='substituted', points to the plan_items.id of the replacement item WITHIN THE SAME PLAN. NULL for non-substituted items. SET NULL if replacement item is deleted.
	SubstitutedBy *uuid.UUID `json:"substituted_by"`
	// The attempt that triggered plan-item completion. FK to attempts(id). NULL for planned/skipped/substituted items, and for manually completed items (e.g., completed outside a session or on another platform with no attempt record). Policy: when Claude marks an item completed via manage_plan, this field is MANDATORY (enforced by policy, not schema). Schema stays nullable to allow future manual/UI completion paths. SET NULL on attempt deletion — completion decision survives.
	CompletedByAttemptID *uuid.UUID `json:"completed_by_attempt_id"`
	// Context for status transitions. For completed: what attempt outcome and reasoning informed the completion decision (policy-mandatory when Claude completes). For skipped/substituted: why the item was removed from active tracking. NULL for planned items only.
	Reason *string `json:"reason"`
	// When this item was added to the plan.
	AddedAt time.Time `json:"added_at"`
	// When this item was marked completed in the plan context. NULL until status → completed. Set by manage_plan tool call, not derived from attempts.
	CompletedAt *time.Time `json:"completed_at"`
}

// Session orchestration boundary — explicit start/end, mode, and attempt container. Distinct from agent_notes: agent_notes are post-hoc narrative (plan, context, reflection), sessions are in-progress orchestration. A session ending may produce an agent_notes(kind=reflection) entry, linked via agent_note_id. updated_at tracks mutation: ended_at and agent_note_id are written by EndSession, and metadata may be updated mid-session by orchestration code.
type LearningSession struct {
	ID uuid.UUID `json:"id"`
	// Learning domain for this session (same convention as concepts.domain).
	Domain string `json:"domain"`
	// retrieval: recall-based testing (no hints). practice: active problem-solving with coaching. mixed: combination of retrieval and practice. review: revisiting previously solved items. reading: comprehension-focused (DDIA, O'Reilly, literary texts).
	SessionMode string `json:"session_mode"`
	// Optional link to the reflection agent_notes entry written after the session. The session produces the note, not the other way around. SET NULL on note deletion.
	AgentNoteID *int64 `json:"agent_note_id"`
	// If this session was planned in the daily plan, link here. Enables plan adherence analysis. SET NULL on plan item deletion.
	DailyPlanItemID *uuid.UUID `json:"daily_plan_item_id"`
	// Session start time. DEFAULT now() for immediate starts.
	StartedAt time.Time `json:"started_at"`
	// NULL until session ends. NULL + old started_at = abandoned/crashed session.
	EndedAt *time.Time `json:"ended_at"`
	// Session orchestration details: coaching prompt used, session summary, configuration. Not queryable — stays in JSONB.
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries (notably EndSession).
	UpdatedAt time.Time `json:"updated_at"`
}

// Learning targets — what to learn, practice, and revisit. Lifecycle differs from notes: items follow not-attempted → practicing → mastered (learning progress), while notes follow seed → evergreen → archived (knowledge maturity). Items exist before notes are written.
type LearningTarget struct {
	ID uuid.UUID `json:"id"`
	// Learning domain (same convention as concepts.domain). Go-validated, not DB-enforced.
	Domain string `json:"domain"`
	// Display title. LeetCode: problem name. Reading: chapter title. Japanese: grammar point or drill name.
	Title string `json:"title"`
	// Provider-specific identifier. LeetCode problem number, textbook section ID, JLPT grammar point ID. NULL for custom drills without external identity. Partial unique: one item per (domain, external_id) where external_id IS NOT NULL.
	ExternalID *string `json:"external_id"`
	// Generic 3-tier difficulty. Domain-specific info (JLPT N5-N1, etc.) goes in metadata. NULL = not categorized. Consistent with notes.difficulty CHECK.
	Difficulty *string `json:"difficulty"`
	// Optional link to the item-level summary note (e.g. a LeetCode solve note). Distinct from learning_attempts.obsidian_note_id which links to an attempt-level working note. SET NULL on note deletion — the item persists without its note.
	ObsidianNoteID *int64 `json:"obsidian_note_id"`
	// Rare — for when a published article/essay is itself a learning target. Most items will not have this. SET NULL on content deletion.
	ContentID *uuid.UUID `json:"content_id"`
	// Optional PARA project association for catalog-level grouping. Plan membership and ordering is tracked via plan_items, not this FK. SET NULL on project deletion — the item persists without its project.
	ProjectID *uuid.UUID `json:"project_id"`
	// Domain-specific data not needing WHERE/JOIN/GROUP BY. Not queryable — if a field needs WHERE/JOIN/GROUP BY, promote to a column. LeetCode: {problem_url, companies, frequency, constraints}. Japanese: {jlpt_level, textbook, chapter, grammar_point}. System Design: {source_book, chapter, scenario_type}. Reading: {book_title, chapter, page_range}.
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Junction: which concepts a learning item exercises. A LeetCode problem's primary concept is two-pointers; secondary might include hash-map. CASCADE on both sides — deleting an item or concept removes the association.
type LearningTargetConcept struct {
	LearningTargetID uuid.UUID `json:"learning_target_id"`
	ConceptID        uuid.UUID `json:"concept_id"`
	// primary: the core concept this item drills. secondary: a supporting concept also exercised. Convention: one primary per item. Multiple primaries should be rare; if frequent, revisit the relevance model.
	Relevance string    `json:"relevance"`
	CreatedAt time.Time `json:"created_at"`
}

// Directed graph of learning target relationships. Direction: anchor is the reference point, related is the other target, relation_type describes how related relates to anchor. Example: (anchor=42, related=167, easier_variant) means "167 is an easier variant of 42." CASCADE on both sides. Append-only — no updated_at. APPLICATION INVARIANT: contradictory pairs (e.g. same ordered pair with both easier_variant and harder_variant) and symmetric conflicts (e.g. mutual prerequisite) are not DDL-enforced — Go validation must prevent them during post-session analysis. Same-domain invariant: both targets must share the same domain — enforced by Go, not DB.
type LearningTargetRelation struct {
	ID uuid.UUID `json:"id"`
	// The reference target (e.g. the one you struggled with). CASCADE on deletion. Renamed from source_item_id to avoid colliding with the table's own "learning_target" semantics.
	AnchorID uuid.UUID `json:"anchor_id"`
	// The other target related to the anchor (e.g. the easier variant to try). CASCADE on deletion. Renamed from target_item_id for the same reason.
	RelatedID uuid.UUID `json:"related_id"`
	// How the related target relates to the anchor. easier_variant: related is simpler (same concept, lower difficulty). harder_variant: related is more complex. prerequisite: related should be done before anchor (e.g. anchor=hard_problem, related=easy_problem, prerequisite = "do easy_problem before attempting hard_problem"). follow_up: related is a natural next step after anchor. same_pattern: related uses the same core pattern. similar_structure: related has structural similarity (different pattern).
	RelationType string    `json:"relation_type"`
	CreatedAt    time.Time `json:"created_at"`
}

// Goal progress checkpoints — binary completion markers within a goal. Milestones and projects are siblings under a goal: a project advances a goal through work, a milestone marks progress. Completion determined by completed_at IS NOT NULL — no separate status column. Goal progress = completed milestones / total milestones (advisory, not auto-derived). NOT OKR Key Results — milestones are binary (done/not-done), not quantitative metrics with target_value/current_value.
type Milestone struct {
	ID uuid.UUID `json:"id"`
	// Descriptive, measurable checkpoint name (e.g. "N3 合格", "API layer complete"). UNIQUE per goal — no duplicate milestone names within the same goal.
	Title string `json:"title"`
	// Detail on what this milestone means and how to measure achievement. Empty string = no detail provided.
	Description string `json:"description"`
	// Parent goal. NOT NULL — every milestone must belong to a goal. CASCADE on delete.
	GoalID uuid.UUID `json:"goal_id"`
	// Target completion date. NULL = no time target (pure checkpoint). Enables mid-goal on-track/at-risk analysis in weekly summary.
	TargetDeadline *time.Time `json:"target_deadline"`
	// When this milestone was achieved. NULL = not yet completed. This is the sole completion indicator — no status enum.
	CompletedAt *time.Time `json:"completed_at"`
	// External system this milestone is synced from (e.g. "notion"). NULL = local-only. Paired with external_ref via chk_milestone_external_pair.
	ExternalProvider *string `json:"external_provider"`
	// Provider-specific identifier within external_provider. NULL = not synced. UNIQUE per provider via uniq_milestone_external.
	ExternalRef *string `json:"external_ref"`
	// Sequence position within a goal (0-based). Convention: position is the gap-free sequence index a row holds inside its parent; sort_order is the priority tier used for top-level UI ordering. See top-of-file ordering convention block.
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Knowledge artifacts synced from an Obsidian vault. Renamed from `notes` in the schema normalization pass to stand in clear contrast to agent_notes (agent narrative log). Nullable columns (title, type, provenance, context, content_text, content_hash, raw_tags) represent optional frontmatter fields — NULL means the field was absent in the source file.
type ObsidianNote struct {
	ID       int64   `json:"id"`
	FilePath string  `json:"file_path"`
	Title    *string `json:"title"`
	// Note type from frontmatter (e.g. leetcode, book-note, dev-log, til). Open-ended — values defined by vault conventions.
	Type *string `json:"type"`
	// Knowledge provenance label (e.g. leetcode, claude, oreilly, ardanlabs). Renamed from `source` to disambiguate from events.source (origin system) and tasks.requester (origin agent). The sync origin (vault system) is implicit in file_path.
	Provenance *string `json:"provenance"`
	// Project or domain context (e.g. project slug). QUASI-CANONICAL — comes from frontmatter (raw), but actively used by MCP search filtering and morning_context. Not FK because vault may reference projects not yet in DB. Treat as soft reference, not pure raw field.
	Context *string `json:"context"`
	// Zettelkasten maturity: seed (new), stub (incomplete), evergreen (mature), archived.
	Maturity string `json:"maturity"`
	// Raw frontmatter tags (JSONB array). Ingestion snapshot — canonical mapping via obsidian_note_tags junction + tag_aliases pipeline.
	RawTags json.RawMessage `json:"raw_tags"`
	// Problem difficulty. Primarily for LeetCode notes.
	Difficulty *string `json:"difficulty"`
	// LeetCode problem number. NULL for non-LeetCode notes.
	LeetcodeID *int32 `json:"leetcode_id"`
	// Book title if this note is from a book reading session.
	Book *string `json:"book"`
	// Chapter identifier within the book.
	Chapter *string `json:"chapter"`
	// External system this note is associated with (e.g. "notion" for a linked Notion task). NULL = standalone vault note. Paired with external_ref via chk_obsidian_note_external_pair. Replaces the previous notion_task_id field — generalised because koopa0.dev is moving away from Notion.
	ExternalProvider *string `json:"external_provider"`
	// Provider-specific identifier within external_provider. NULL = no external link.
	ExternalRef *string `json:"external_ref"`
	// Full text content extracted from the note file. Used for full-text search.
	ContentText *string `json:"content_text"`
	// SHA-256 hex of content_text (chk_obsidian_note_content_hash_format). Used for change detection during sync — skip re-processing if unchanged.
	ContentHash *string `json:"content_hash"`
	// pgvector embedding (768d) for semantic search via HNSW index.
	Embedding *pgvector_go.Vector `json:"embedding"`
	// Generated tsvector for full-text search. Uses 'simple' config — same rationale as contents.search_vector.
	SearchVector interface{} `json:"search_vector"`
	// File creation time from git log. NULL if not tracked by git.
	GitCreatedAt *time.Time `json:"git_created_at"`
	// File last modification time from git log. NULL if not tracked by git.
	GitUpdatedAt *time.Time `json:"git_updated_at"`
	// When this note was last synced from the vault.
	SyncedAt time.Time `json:"synced_at"`
}

// Wikilink edges between obsidian notes. Drives the knowledge graph API.
type ObsidianNoteLink struct {
	ID           int64 `json:"id"`
	SourceNoteID int64 `json:"source_note_id"`
	// Wikilink target file path. May reference notes not yet synced — forward/broken links expected.
	TargetPath string    `json:"target_path"`
	LinkText   *string   `json:"link_text"`
	CreatedAt  time.Time `json:"created_at"`
}

// Junction: obsidian note ↔ canonical tag. Many-to-many. Tags resolved from raw_tags via tag_aliases pipeline.
type ObsidianNoteTag struct {
	ObsidianNoteID int64     `json:"obsidian_note_id"`
	TagID          uuid.UUID `json:"tag_id"`
}

// PARA projects — short-term efforts with a clear outcome. Projects and milestones are siblings under a goal: a project may advance a goal without mapping to a specific milestone. Includes portfolio/case study fields for public display.
type Project struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	// Extended description for project detail page. NULL = use description.
	LongDescription *string `json:"long_description"`
	// User role in this project (e.g. Lead Engineer, Sole Developer). NULL = not specified.
	Role       *string  `json:"role"`
	TechStack  []string `json:"tech_stack"`
	Highlights []string `json:"highlights"`
	// Case study: what problem this project solves. NULL = not a case study.
	Problem *string `json:"problem"`
	// Case study: how the problem was solved.
	Solution *string `json:"solution"`
	// Case study: system architecture description.
	Architecture *string `json:"architecture"`
	// Case study: measurable outcomes.
	Results *string `json:"results"`
	// Full GitHub repository URL. NULL = no public repo.
	GithubUrl *string `json:"github_url"`
	// Production deployment URL. NULL = not deployed.
	LiveUrl *string `json:"live_url"`
	// Whether to show on the public portfolio homepage.
	Featured bool `json:"featured"`
	// Whether this project is visible on the public website.
	IsPublic  bool          `json:"is_public"`
	SortOrder int32         `json:"sort_order"`
	Status    ProjectStatus `json:"status"`
	// External system this project is synced from (e.g. "notion"). NULL = local-only. Paired with external_ref via chk_project_external_pair.
	ExternalProvider *string `json:"external_provider"`
	// Provider-specific identifier within external_provider. NULL = not synced. UNIQUE per provider via uniq_project_external.
	ExternalRef *string `json:"external_ref"`
	// GitHub repository full name (e.g. Koopa0/koopa0.dev). Used by activity event resolution and webhook routing.
	Repo *string `json:"repo"`
	// PARA Area of Responsibility. FK to areas. SET NULL on area deletion. NULL = unclassified.
	AreaID *uuid.UUID `json:"area_id"`
	// Which goal this project serves. Nullable — a project can exist without a goal (PARA: some projects are pure Area maintenance, not goal-driven). SET NULL on goal deletion.
	GoalID   *uuid.UUID `json:"goal_id"`
	Deadline *time.Time `json:"deadline"`
	// Timestamp of most recent activity event for this project. Updated by cron.
	LastActivityAt *time.Time `json:"last_activity_at"`
	// Expected development activity frequency. NULL = not set.
	ExpectedCadence *string   `json:"expected_cadence"`
	CreatedAt       time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Maps variant project names to canonical project. Used by activity event and MCP search to resolve fuzzy project references.
type ProjectAlias struct {
	ID uuid.UUID `json:"id"`
	// Variant name (e.g. repo name, Notion title variant). Case-insensitive unique — "Koopa0.dev" and "koopa0.dev" are the same alias.
	Alias string `json:"alias"`
	// References canonical project. CASCADE — aliases meaningless without project.
	ProjectID uuid.UUID `json:"project_id"`
	// Where this alias was discovered (e.g. github, notion, manual).
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

// JWT refresh token hashes. One user may have multiple active tokens (multi-device).
type RefreshToken struct {
	ID uuid.UUID `json:"id"`
	// Token owner. CASCADE — user deletion invalidates all tokens.
	UserID uuid.UUID `json:"user_id"`
	// Bcrypt or SHA256 hash of the actual token. Never store plaintext.
	TokenHash string `json:"token_hash"`
	// Absolute expiration. Tokens past this time are invalid and eligible for cleanup.
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Spaced repetition card state. Algorithm-agnostic — currently FSRS. Two target types: content-based (article/note recall) and learning-item-based (problem/drill retention). Exactly one of content_id or learning_target_id must be NOT NULL, enforced by chk_review_target_exactly_one. FSRS engine is target-agnostic — it operates on (card_state, rating) → new_card_state regardless of target type.
type ReviewCard struct {
	ID int64 `json:"id"`
	// Content-based review target. NULL when this card targets a learning item. Mutually exclusive with learning_target_id (checked by chk_review_target_exactly_one). CASCADE — deleting the content deletes its review cards.
	ContentID *uuid.UUID `json:"content_id"`
	// Learning-item-based review target (problem, drill, chapter). NULL when this card targets content. Mutually exclusive with content_id. CASCADE — deleting the item deletes its review cards.
	LearningTargetID *uuid.UUID `json:"learning_target_id"`
	// Canonical tag for per-concept review within content-based cards. NULL = whole-content review. Only meaningful when content_id IS NOT NULL, enforced by chk_tag_requires_content. CASCADE on tag deletion — SET NULL would risk violating idx_review_cards_content_whole unique constraint if a whole-content card already exists for the same content. Application layer should warn before tag deletion (FSRS state is lost).
	TagID *uuid.UUID `json:"tag_id"`
	// Serialized algorithm state (Due, Stability, Difficulty, Reps, Lapses). Opaque to SQL.
	CardState []byte `json:"card_state"`
	// Denormalized from card_state for index-based due-date queries.
	Due       time.Time `json:"due"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries (after FSRS review).
	UpdatedAt time.Time `json:"updated_at"`
}

// Append-only review history. One row per review event.
type ReviewLog struct {
	ID int64 `json:"id"`
	// The review card this log belongs to. CASCADE — card deletion removes its history.
	CardID int64 `json:"card_id"`
	// 1=Again (forgot), 2=Hard (partial), 3=Good (remembered), 4=Easy.
	Rating int32 `json:"rating"`
	// Days the FSRS algorithm scheduled between this and the previous review.
	ScheduledDays int32 `json:"scheduled_days"`
	// Actual days elapsed since the previous review.
	ElapsedDays int32 `json:"elapsed_days"`
	// Card state BEFORE this review: 0=New, 1=Learning, 2=Review, 3=Relearning.
	State int32 `json:"state"`
	// When this review occurred. May differ from row insertion time if backfilled. DEFAULT now() for real-time reviews.
	ReviewedAt time.Time `json:"reviewed_at"`
}

// External data source sync configuration. Provider column distinguishes Notion, Linear, etc. UPGRADE PATH: when a second provider is added for the same role (e.g. Google Calendar for tasks), change UNIQUE(role) to UNIQUE(provider, role) to allow multiple sources per role.
type SyncSource struct {
	ID uuid.UUID `json:"id"`
	// Identifier in the external system (e.g. Notion database ID). UNIQUE — one source config per external resource.
	ExternalID  string `json:"external_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// Which external platform this source connects to.
	Provider string `json:"provider"`
	// What kind of data this source provides. NULL = not categorized. UNIQUE partial index — one source per role.
	Role *string `json:"role"`
	// Sync strategy: full (re-sync all), incremental (changes only).
	SyncMode string `json:"sync_mode"`
	// Maps external properties to local fields (JSONB). Structure varies by provider and role.
	PropertyMap []byte `json:"property_map"`
	// How often to poll for changes. PostgreSQL INTERVAL type — DB validates format.
	PollInterval pgtype.Interval `json:"poll_interval"`
	Enabled      bool            `json:"enabled"`
	// Last successful sync timestamp. NULL = never synced.
	LastSyncedAt *time.Time `json:"last_synced_at"`
	CreatedAt    time.Time  `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}

// Canonical tag registry. Fine-grained labels (two-pointers, error-handling). Auto-extracted from obsidian notes, resolved through tag_aliases pipeline.
type Tag struct {
	ID uuid.UUID `json:"id"`
	// Canonical form (e.g. two-pointers, dp). Controlled vocabulary for LeetCode patterns. Format: standard slug, OR namespaced slug like weakness:state-transition / improvement:edge-cases (chk_tag_slug_format).
	Slug string `json:"slug"`
	Name string `json:"name"`
	// Hierarchical parent tag. SET NULL on parent deletion — orphaned tags remain valid.
	ParentID    *uuid.UUID `json:"parent_id"`
	Description string     `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// Maps raw tag strings (from frontmatter/external) to canonical tags. Pipeline: raw_tag → lookup alias → resolve to tag_id.
type TagAlias struct {
	ID uuid.UUID `json:"id"`
	// Original tag string as found in source (e.g. "golang", "JS", "dynamic-programming").
	RawTag string `json:"raw_tag"`
	// Resolved canonical tag. NULL for unmapped/rejected aliases.
	TagID *uuid.UUID `json:"tag_id"`
	// How the alias was resolved: exact, case-insensitive, manual (admin), unmapped (pending), rejected (admin declined).
	MatchMethod string `json:"match_method"`
	// Whether an admin has verified this mapping. Unconfirmed auto-matches may be wrong.
	Confirmed bool `json:"confirmed"`
	// When an admin confirmed this mapping. NULL iff confirmed = false (enforced by chk_confirmed_pair). Set together with confirmed = true.
	ConfirmedAt *time.Time `json:"confirmed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

// Inter-agent coordination work units (NOT personal GTD todos — those live in todos). One requester agent asks one assignee agent to do work. Lifecycle: submitted → working → completed | canceled. chk_tasks_state_timestamps makes illegal state/timestamp combinations physically impossible at the DB layer, independent of any Go-side validation. Conversation history is stored in task_messages; structured deliverables in artifacts. A completed task must have at least one response message AND at least one artifact — enforced by Go transition logic (Store.Complete), not by DB CHECK, because the multi-table invariant cannot be expressed as a single-row constraint.
type Task struct {
	ID uuid.UUID `json:"id"`
	// Agent that submitted the task. FK to agents — historical references never dangle. Renamed from "source" to align with A2A vocabulary and disambiguate from events.source (origin system).
	Requester string `json:"requester"`
	// Agent expected to perform the work. FK to agents. Renamed from "target" to align with A2A vocabulary.
	Assignee string `json:"assignee"`
	// Short human-readable task label. Non-blank (chk_task_title_not_blank).
	Title string `json:"title"`
	// Lifecycle state. Four values: submitted (created, not yet accepted), working (assignee accepted, in flight), completed (response + artifact delivered), canceled (requester canceled). Failed/rejected/input_required are deferred — no current handler produces them.
	State TaskState `json:"state"`
	// When the requester created this task. DEFAULT now() — always set at insertion time.
	SubmittedAt time.Time `json:"submitted_at"`
	// When the assignee transitioned the task to working. NULL iff state=submitted or canceled-from-submitted (enforced by chk_tasks_state_timestamps).
	AcceptedAt *time.Time `json:"accepted_at"`
	// When the assignee delivered the final response+artifact. NULL unless state=completed.
	CompletedAt *time.Time `json:"completed_at"`
	// When the requester canceled the task. NULL unless state=canceled. Mutually exclusive with completed_at.
	CanceledAt *time.Time `json:"canceled_at"`
	// Non-routing task info: deadline, priority hint, correlation keys. JSONB for flexibility; promote fields to columns when query patterns demand it. TODO(coordination): when query patterns stabilise, promote deadline and correlation_id to first-class columns.
	Metadata []byte `json:"metadata"`
}

// Ordered request/response conversation turns on a task. Parts column is a JSONB array of a2a.Part values (flattened form). Hard size caps (16 parts max, 32 KB total) are DB-enforced bloat prevention — anything larger belongs in artifacts, not messages.
type TaskMessage struct {
	ID uuid.UUID `json:"id"`
	// Parent task. CASCADE — messages die with their task.
	TaskID uuid.UUID `json:"task_id"`
	// request = message from requester to assignee. response = message from assignee back to requester. Two values only; system messages are deferred until a real use case appears.
	Role MessageRole `json:"role"`
	// Order within a task conversation, 0-based. UNIQUE(task_id, position) prevents duplicates and out-of-order inserts.
	Position int32 `json:"position"`
	// JSONB array of a2a.Part values in a2a-go's flattened format. Each part is {"text": "..."} or {"data": {...}}. Serialized/deserialized by a2a-go — Go code never hand-rolls this shape.
	Parts []byte `json:"parts"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// Personal GTD work items. Distinct from the tasks coordination entity (inter-agent work units). Lifecycle: inbox (captured, not clarified) → todo (clarified, actionable) → in_progress → done. someday = interested but not now, reviewed in Weekly Review. inbox items lack project/due/priority — clarification promotes them to todo.
type Todo struct {
	ID uuid.UUID `json:"id"`
	// Short summary of the todo. Non-blank (chk_todo_title_not_blank).
	Title string `json:"title"`
	// GTD lifecycle: inbox → todo | someday. todo → in_progress → done. inbox = captured but not clarified (missing project/due/priority). someday = interested but not acting now — reviewed periodically.
	State TodoState `json:"state"`
	// Due date. NULL = no deadline.
	Due *time.Time `json:"due"`
	// Optional parent project. SET NULL on project deletion — the todo survives unclassified.
	ProjectID        *uuid.UUID `json:"project_id"`
	ExternalProvider *string    `json:"external_provider"`
	ExternalRef      *string    `json:"external_ref"`
	// When the todo was completed. NULL unless state=done, enforced by chk_todo_completed_at_consistency.
	CompletedAt *time.Time `json:"completed_at"`
	// Required energy level for GTD engage-by-energy. NULL = not set.
	Energy *string `json:"energy"`
	// Todo priority for GTD engage-by-priority. NULL = not set.
	Priority *string `json:"priority"`
	// Recurrence frequency count. NULL = non-recurring. Paired with recur_unit by chk_todo_recurrence_pair.
	RecurInterval *int32 `json:"recur_interval"`
	// Recurrence unit. NULL = non-recurring todo.
	RecurUnit *string `json:"recur_unit"`
	// Free-text detail. Empty string = no detail.
	Description string `json:"description"`
	// Agent responsible for executing this todo. FK to agents. Default human. Capability enforcement is Go-side (agent.Authorize), not DB-side.
	Assignee string `json:"assignee"`
	// Which agent created or imported this todo into the system. FK to agents. Default human. Examples: human (manual or synced from external tool), hq (morning briefing).
	CreatedBy string `json:"created_by"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
	// Set explicitly by application in UPDATE queries. No trigger — application-managed.
	UpdatedAt time.Time `json:"updated_at"`
}

// Per-occurrence skip history for recurring todo items.
type TodoSkip struct {
	ID uuid.UUID `json:"id"`
	// Which recurring todo was skipped. CASCADE — skips die with their todo.
	TodoID uuid.UUID `json:"todo_id"`
	// Due date when skip was detected by cron.
	OriginalDue time.Time `json:"original_due"`
	// The occurrence date that was missed.
	SkippedDate time.Time `json:"skipped_date"`
	// auto-expired (cron detected overdue) or manual (user skipped).
	Reason string `json:"reason"`
	// Row insertion timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// High-level knowledge domains (Go, AI, System Design). 10-20, manually managed. Used for content categorization and feed association.
type Topic struct {
	ID uuid.UUID `json:"id"`
	// URL-safe identifier (e.g. system-design). Used in feed_topics and content_topics junctions. Format: lowercase alphanumeric segments separated by single hyphens (chk_topic_slug_format) — no consecutive or trailing hyphens.
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// Optional emoji or icon identifier for UI display.
	Icon *string `json:"icon"`
	// Priority tier for display ordering (lower = higher priority). Convention: sort_order is for tier-based UI placement that may have gaps; position is for sequence-based 0-based indexing within a parent. See top-of-file ordering convention block.
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Active monitoring rules per topic. Keywords drive web search, schedule controls frequency. One monitor per topic max. Name comes from topics.name — not duplicated here.
type TopicMonitor struct {
	ID      uuid.UUID `json:"id"`
	TopicID uuid.UUID `json:"topic_id"`
	// Search keywords for this topic. Used by monitoring pipeline to discover new content.
	Keywords []string `json:"keywords"`
	// Specific source URLs or domains to monitor for this topic.
	Sources []string `json:"sources"`
	// Cron expression string (e.g. "0 */6 * * *"). Format validated by the Go scheduler — DB only enforces non-blank via chk_topic_monitor_schedule_not_blank. NOT a label like feeds.schedule.
	Schedule  string    `json:"schedule"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// System users. Currently single-admin only.
type User struct {
	ID uuid.UUID `json:"id"`
	// Login identity. Unique. Basic structural validation via chk_users_email_format (full RFC 5322 compliance is enforced at the application layer).
	Email string `json:"email"`
	// Single-value placeholder. Currently only admin exists. If no second role materializes by public API launch, delete this column. CHECK uses IN() syntax for easy extension.
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	// Application-managed. Set explicitly in UPDATE queries.
	UpdatedAt time.Time `json:"updated_at"`
}
